[advisories]
unmaintained = "workspace"
ignore = [
    "RUSTSEC-2025-0012", # backoff: 已有依赖，待 migrate 到 backon
]

[licenses]
private = { ignore = true }
allow = [
    "MIT",
    "MIT-0",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "CC0-1.0",
    "Unicode-3.0",
    "MPL-2.0",
    "OpenSSL",
    "AGPL-3.0-only",
    "BSL-1.0",
    "NCSA",
    "CDLA-Permissive-2.0",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
