edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
use_small_heuristics = "Max"
reorder_imports = true
match_block_trailing_comma = true
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
fn_params_layout = "Tall"
