edition = "2021"
max_width = 100
use_small_heuristics = "Max"
format_strings = true
reorder_imports = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
fn_call_width = 80
attr_fn_like_width = 80
struct_lit_width = 18
struct_variant_width = 35
array_width = 60
chain_width = 60
single_line_if_else_max_width = 50
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
format_macro_matchers = true
format_macro_bodies = true
fn_params_layout = "Tall"
