use sea_orm_migration::prelude::*;

/// 补齐 entity 模型中已定义但迁移中缺失的表：
/// - gateway_links / gateway_link_policies / gateway_link_activities
/// - generated_tools
/// - scheduled_tasks
pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20240101_000003_init_gateway_tools"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // ── 1. gateway_links ──
        manager
            .create_table(
                Table::create()
                    .table(GatewayLinks::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(GatewayLinks::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(GatewayLinks::Name).string().not_null())
                    .col(ColumnDef::new(GatewayLinks::LinkType).string().not_null())
                    .col(ColumnDef::new(GatewayLinks::Endpoint).string().not_null())
                    .col(ColumnDef::new(GatewayLinks::ApiKeyId).string().null())
                    .col(
                        ColumnDef::new(GatewayLinks::Enabled)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(GatewayLinks::Status)
                            .string()
                            .not_null()
                            .default("disconnected"),
                    )
                    .col(ColumnDef::new(GatewayLinks::ErrorMessage).string().null())
                    .col(
                        ColumnDef::new(GatewayLinks::AutoSyncModels)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(GatewayLinks::AutoSyncSkills)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(GatewayLinks::LastSyncAt)
                            .big_integer()
                            .null(),
                    )
                    .col(ColumnDef::new(GatewayLinks::LatencyMs).big_integer().null())
                    .col(ColumnDef::new(GatewayLinks::Version).string().null())
                    .col(
                        ColumnDef::new(GatewayLinks::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinks::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 3. gateway_link_policies ──
        manager
            .create_table(
                Table::create()
                    .table(GatewayLinkPolicies::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::LinkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::RouteStrategy)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::ModelFallbackEnabled)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::GlobalRpm)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::PerModelRpm)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::TokenLimitPerMinute)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::KeyRotationStrategy)
                            .string()
                            .not_null()
                            .default("round_robin"),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkPolicies::KeyFailoverEnabled)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 4. gateway_link_activities ──
        manager
            .create_table(
                Table::create()
                    .table(GatewayLinkActivities::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(GatewayLinkActivities::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkActivities::LinkId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkActivities::ActivityType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkActivities::Description)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(GatewayLinkActivities::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 5. generated_tools ──
        manager
            .create_table(
                Table::create()
                    .table(GeneratedTools::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(GeneratedTools::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(GeneratedTools::ToolName).string().not_null())
                    .col(
                        ColumnDef::new(GeneratedTools::OriginalName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::OriginalDescription)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::InputSchema)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::OutputSchema)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::Implementation)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::SourceInfo)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(GeneratedTools::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 6. scheduled_tasks ──
        manager
            .create_table(
                Table::create()
                    .table(ScheduledTasks::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ScheduledTasks::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ScheduledTasks::Name).string().not_null())
                    .col(
                        ColumnDef::new(ScheduledTasks::Description)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ScheduledTasks::TaskType).text().not_null())
                    .col(ColumnDef::new(ScheduledTasks::WorkflowId).string().null())
                    .col(
                        ColumnDef::new(ScheduledTasks::CronExpression)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ScheduledTasks::IntervalSeconds)
                            .big_integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(ScheduledTasks::NextRunAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScheduledTasks::LastRunAt)
                            .big_integer()
                            .null(),
                    )
                    .col(ColumnDef::new(ScheduledTasks::LastResult).string().null())
                    .col(ColumnDef::new(ScheduledTasks::Status).text().not_null())
                    .col(ColumnDef::new(ScheduledTasks::Config).text().not_null())
                    .col(
                        ColumnDef::new(ScheduledTasks::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ScheduledTasks::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(ScheduledTasks::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(GeneratedTools::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(GatewayLinkActivities::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(GatewayLinkPolicies::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(GatewayLinks::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum GatewayLinks {
    Table,
    Id,
    Name,
    LinkType,
    Endpoint,
    ApiKeyId,
    Enabled,
    Status,
    ErrorMessage,
    AutoSyncModels,
    AutoSyncSkills,
    LastSyncAt,
    LatencyMs,
    Version,
    CreatedAt,
    UpdatedAt,
}
#[derive(Iden)]
enum GatewayLinkPolicies {
    Table,
    Id,
    LinkId,
    RouteStrategy,
    ModelFallbackEnabled,
    GlobalRpm,
    PerModelRpm,
    TokenLimitPerMinute,
    KeyRotationStrategy,
    KeyFailoverEnabled,
}
#[derive(Iden)]
enum GatewayLinkActivities {
    Table,
    Id,
    LinkId,
    ActivityType,
    Description,
    CreatedAt,
}
#[derive(Iden)]
enum GeneratedTools {
    Table,
    Id,
    ToolName,
    OriginalName,
    OriginalDescription,
    InputSchema,
    OutputSchema,
    Implementation,
    SourceInfo,
    CreatedAt,
}
#[derive(Iden)]
enum ScheduledTasks {
    Table,
    Id,
    Name,
    Description,
    TaskType,
    WorkflowId,
    CronExpression,
    IntervalSeconds,
    NextRunAt,
    LastRunAt,
    LastResult,
    Status,
    Config,
    CreatedAt,
    UpdatedAt,
}
