use sea_orm_migration::prelude::*;

/// 创建工作流系统需要的表：
/// - workflow_templates         模板主表
/// - workflow_template_versions  模板版本历史
/// - workflow_executions         工作流执行记录
/// - workflow_marketplace        工作流市场
/// - workflow_marketplace_reviews 市场评价
pub struct Migration;

impl MigrationName for Migration {
    fn name(&self) -> &str {
        "m20240101_000002_init_workflow"
    }
}

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // ── 1. workflow_templates ──
        manager
            .create_table(
                Table::create()
                    .table(WorkflowTemplates::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WorkflowTemplates::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(WorkflowTemplates::Name).string().not_null())
                    .col(
                        ColumnDef::new(WorkflowTemplates::Description)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::Icon)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(WorkflowTemplates::Tags).string().null())
                    .col(
                        ColumnDef::new(WorkflowTemplates::Version)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::IsPreset)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::IsEditable)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::IsPublic)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::TriggerConfig)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(WorkflowTemplates::Nodes).text().not_null())
                    .col(ColumnDef::new(WorkflowTemplates::Edges).text().not_null())
                    .col(
                        ColumnDef::new(WorkflowTemplates::InputSchema)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::OutputSchema)
                            .string()
                            .null(),
                    )
                    .col(ColumnDef::new(WorkflowTemplates::Variables).string().null())
                    .col(
                        ColumnDef::new(WorkflowTemplates::ErrorConfig)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::CompositeSource)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplates::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 2. workflow_template_versions ──
        manager
            .create_table(
                Table::create()
                    .table(WorkflowTemplateVersions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::TemplateId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Description)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Icon)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Tags)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Version)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::IsPreset)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::IsEditable)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::IsPublic)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::TriggerConfig)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Nodes)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Edges)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::InputSchema)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::OutputSchema)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::Variables)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::ErrorConfig)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowTemplateVersions::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 3. workflow_executions ──
        manager
            .create_table(
                Table::create()
                    .table(WorkflowExecutions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WorkflowExecutions::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::WorkflowId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::Status)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::InputParams)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::OutputResult)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::NodeExecutions)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::TotalTimeMs)
                            .integer()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowExecutions::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 4. workflow_marketplace ──
        manager
            .create_table(
                Table::create()
                    .table(WorkflowMarketplace::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::TemplateId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::AuthorId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Description)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Category)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Icon)
                            .string()
                            .not_null()
                            .default(""),
                    )
                    .col(ColumnDef::new(WorkflowMarketplace::Tags).string().null())
                    .col(
                        ColumnDef::new(WorkflowMarketplace::Downloads)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::RatingAverage)
                            .double()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::RatingCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::IsFeatured)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::IsVerified)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::IsPublic)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplace::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── 5. workflow_marketplace_reviews ──
        manager
            .create_table(
                Table::create()
                    .table(WorkflowMarketplaceReviews::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::MarketplaceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::UserId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::Rating)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::Comment)
                            .string()
                            .null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::IsHidden)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::CreatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(WorkflowMarketplaceReviews::UpdatedAt)
                            .big_integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(WorkflowMarketplaceReviews::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(WorkflowMarketplace::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(WorkflowExecutions::Table).to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(WorkflowTemplateVersions::Table)
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(WorkflowTemplates::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum WorkflowTemplates {
    Table,
    Id,
    Name,
    Description,
    Icon,
    Tags,
    Version,
    IsPreset,
    IsEditable,
    IsPublic,
    TriggerConfig,
    Nodes,
    Edges,
    InputSchema,
    OutputSchema,
    Variables,
    ErrorConfig,
    CompositeSource,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WorkflowTemplateVersions {
    Table,
    Id,
    TemplateId,
    Name,
    Description,
    Icon,
    Tags,
    Version,
    IsPreset,
    IsEditable,
    IsPublic,
    TriggerConfig,
    Nodes,
    Edges,
    InputSchema,
    OutputSchema,
    Variables,
    ErrorConfig,
    CreatedAt,
}

#[derive(Iden)]
enum WorkflowExecutions {
    Table,
    Id,
    WorkflowId,
    Status,
    InputParams,
    OutputResult,
    NodeExecutions,
    TotalTimeMs,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WorkflowMarketplace {
    Table,
    Id,
    TemplateId,
    AuthorId,
    Name,
    Description,
    Category,
    Icon,
    Tags,
    Downloads,
    RatingAverage,
    RatingCount,
    IsFeatured,
    IsVerified,
    IsPublic,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum WorkflowMarketplaceReviews {
    Table,
    Id,
    MarketplaceId,
    UserId,
    Rating,
    Comment,
    IsHidden,
    CreatedAt,
    UpdatedAt,
}
