[package]
name = "axagent-providers"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = "1"
async-trait = "0.1"
axagent-core = { path = "../core" }
axagent-harness = { path = "../harness" }
futures = "0.3"
reqwest = { workspace = true, features = ["stream", "socks", "rustls", "native-tls-vendored"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { version = "0.29", features = ["native-tls"] }
tracing = { workspace = true }
uuid = { workspace = true }
