import { PlusOutlined, ReloadOutlined, SearchOutlined } from "@ant-design/icons";
import { Button, Empty, Input, Select, Space, Switch, Table, Tag, Typography } from "antd";
import React, { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { useAtomicSkillStore } from "../../stores/feature/atomicSkillStore";
import type { AtomicSkill } from "../../types";

const { Text } = Typography;

interface AtomicSkillListProps {
  onEdit?: (skill: AtomicSkill) => void;
  onCreate?: () => void;
}

const ENTRY_TYPE_COLORS: Record<string, string> = {
  builtin: "blue",
  mcp: "purple",
  local: "green",
  plugin: "orange",
};

const getEntryTypeLabel = (entryType: string, t: (key: string) => string) => {
  switch (entryType) {
    case "builtin":
      return t("atomicSkill.entryTypeBuiltin");
    case "mcp":
      return t("atomicSkill.entryTypeMcp");
    case "local":
      return t("atomicSkill.entryTypeLocal");
    case "plugin":
      return t("atomicSkill.entryTypePlugin");
    default:
      return entryType;
  }
};

export const AtomicSkillList: React.FC<AtomicSkillListProps> = ({ onEdit, onCreate }) => {
  const { t } = useTranslation();
  const { skills, loading, loadSkills, toggleSkill, filter, setFilter } = useAtomicSkillStore();
  const [searchText, setSearchText] = useState("");

  useEffect(() => {
    loadSkills();
  }, [loadSkills]);

  const filteredSkills = skills.filter((s) =>
    !searchText || s.name.toLowerCase().includes(searchText.toLowerCase())
    || s.description.toLowerCase().includes(searchText.toLowerCase())
  );

  const columns = [
    {
      title: t("common.name"),
      dataIndex: "name",
      key: "name",
      render: (name: string, record: AtomicSkill) => <a onClick={() => onEdit?.(record)}>{name}</a>,
    },
    {
      title: t("common.description"),
      dataIndex: "description",
      key: "description",
      ellipsis: true,
      render: (desc: string) => <Text type="secondary">{desc}</Text>,
    },
    {
      title: t("common.category"),
      dataIndex: "category",
      key: "category",
      width: 100,
      render: (category: string) => <Tag>{category}</Tag>,
    },
    {
      title: t("atomicSkill.entryType"),
      dataIndex: "entry_type",
      key: "entry_type",
      width: 90,
      render: (entryType: string) => (
        <Tag color={ENTRY_TYPE_COLORS[entryType] || "default"}>
          {getEntryTypeLabel(entryType, t)}
        </Tag>
      ),
    },
    {
      title: t("atomicSkill.source"),
      dataIndex: "source",
      key: "source",
      width: 100,
      render: (source: string) => (
        <Tag color={source === "auto-generated" ? "volcano" : "cyan"}>
          {source === "auto-generated" ? t("atomicSkill.sourceAutoGenerated") : t("atomicSkill.sourceAtomic")}
        </Tag>
      ),
    },
    {
      title: t("common.enabled"),
      dataIndex: "enabled",
      key: "enabled",
      width: 70,
      render: (enabled: boolean, record: AtomicSkill) => (
        <Switch
          size="small"
          checked={enabled}
          onChange={(checked) => toggleSkill(record.id, checked)}
        />
      ),
    },
  ];

  return (
    <div style={{ padding: "0 16px" }}>
      <Space style={{ marginBottom: 16 }} wrap>
        <Input
          placeholder={t("atomicSkill.searchAtomicSkill")}
          prefix={<SearchOutlined />}
          value={searchText}
          onChange={(e) => setSearchText(e.target.value)}
          style={{ width: 240 }}
          allowClear
        />
        <Select
          placeholder={t("common.category")}
          allowClear
          style={{ width: 120 }}
          value={filter.category}
          onChange={(v) => {
            setFilter({ ...filter, category: v });
            loadSkills({ ...filter, category: v });
          }}
          options={[
            { label: t("common.general"), value: "general" },
            { label: t("atomicSkill.decomposed"), value: "decomposed" },
            { label: t("atomicSkill.undecomposed"), value: "undecomposed" },
          ]}
        />
        <Select
          placeholder={t("atomicSkill.source")}
          allowClear
          style={{ width: 120 }}
          value={filter.source}
          onChange={(v) => {
            setFilter({ ...filter, source: v });
            loadSkills({ ...filter, source: v });
          }}
          options={[
            { label: t("atomicSkill.sourceAtomic"), value: "atomic" },
            { label: t("atomicSkill.sourceAutoGenerated"), value: "auto-generated" },
          ]}
        />
        <Button icon={<ReloadOutlined />} onClick={() => loadSkills()}>{t("common.refresh")}</Button>
        {onCreate && <Button type="primary" icon={<PlusOutlined />} onClick={onCreate}>{t("common.create")}</Button>}
      </Space>

      {filteredSkills.length === 0 && !loading ? <Empty description={t("atomicSkill.noAtomicSkills")} /> : (
        <Table
          dataSource={filteredSkills}
          columns={columns}
          rowKey="id"
          loading={loading}
          size="small"
          pagination={{ pageSize: 20, showSizeChanger: false }}
        />
      )}
    </div>
  );
};
