//! 股票分析工作流模板 — 可配置变量定义
//!
//! 拆分自 seed_stock_analysis.rs（P1-5），减少主文件行数 ~1100 行。
//! 变量通过 `{{var}}` 语法注入到 Rhai 脚本和 Agent prompt 中。

use axagent_harness::workflow_types::Variable;

/// 构建股票分析工作流模板的所有可配置变量
pub(crate) fn build_template_variables() -> Vec<Variable> {
    vec![
        // ── 分析流程参数 ──
        Variable {
            name: "analysis_depth".into(),
            var_type: "enum".into(),
            value: serde_json::json!("standard"),
            description: Some("分析深度: quick / standard / deep".into()),
            is_secret: false,
        },
        Variable {
            name: "debate_rounds".into(),
            var_type: "number".into(),
            value: serde_json::json!(3),
            description: Some("多空辩论轮数 (1-10)".into()),
            is_secret: false,
        },
        Variable {
            name: "screening_source".into(),
            var_type: "string".into(),
            value: serde_json::json!(""),
            description: Some("筛选来源标记：serenity(瓶颈掘金) / ''(直接分析)".into()),
            is_secret: false,
        },
        Variable {
            name: "max_concurrent".into(),
            var_type: "number".into(),
            value: serde_json::json!(5),
            description: Some("并行分析的 Agent 数量上限".into()),
            is_secret: false,
        },
        // ── 数据源参数 ──
        Variable {
            name: "kline_period".into(),
            var_type: "enum".into(),
            value: serde_json::json!("daily"),
            description: Some("K线周期: daily / weekly / monthly".into()),
            is_secret: false,
        },
        Variable {
            name: "kline_limit".into(),
            var_type: "number".into(),
            value: serde_json::json!(120),
            description: Some("K线获取根数 (1-500)".into()),
            is_secret: false,
        },
        Variable {
            name: "news_limit".into(),
            var_type: "number".into(),
            value: serde_json::json!(30),
            description: Some("新闻获取条数 (1-100)".into()),
            is_secret: false,
        },
        // ── 行业参照参数（股票分析中 t-baseline-* 节点使用）──
        Variable {
            name: "ref_semi_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("002371"),
            description: Some("半导体行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_battery_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("300750"),
            description: Some("电池行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_chem_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("600309"),
            description: Some("化工行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_med_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("688981"),
            description: Some("医疗行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_aero_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("600760"),
            description: Some("航空军工行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_consumer_elec_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("002475"),
            description: Some("消费电子行业参照股票代码".into()),
            is_secret: false,
        },
        Variable {
            name: "ref_auto_code".into(),
            var_type: "string".into(),
            value: serde_json::json!("600104"),
            description: Some("汽车行业参照股票代码".into()),
            is_secret: false,
        },
        // ── Agent 节点 LLM 参数 ──
        Variable {
            name: "agent_temperature".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.3),
            description: Some("所有 Agent 节点 LLM 温度 (0-2)".into()),
            is_secret: false,
        },
        Variable {
            name: "agent_max_tokens".into(),
            var_type: "number".into(),
            value: serde_json::json!(32768),
            description: Some(
                "所有 Agent 节点最大输出 token 数（模板变量覆盖硬编码默认值）".into(),
            ),
            is_secret: false,
        },
        Variable {
            name: "agent_timeout_secs".into(),
            var_type: "number".into(),
            value: serde_json::json!(600),
            description: Some(
                "每个 Agent 节点执行超时秒数（主控，继承到所有无显式超时的 agent 节点）".into(),
            ),
            is_secret: false,
        },
        Variable {
            name: "agent_retry_max".into(),
            var_type: "number".into(),
            value: serde_json::json!(2),
            description: Some("每个 Agent 节点最大重试次数".into()),
            is_secret: false,
        },
        // ── Tool 节点参数 ──
        Variable {
            name: "tool_timeout_secs".into(),
            var_type: "number".into(),
            value: serde_json::json!(30),
            description: Some("每个 Tool 节点执行超时秒数".into()),
            is_secret: false,
        },
        Variable {
            name: "tool_retry_max".into(),
            var_type: "number".into(),
            value: serde_json::json!(2),
            description: Some("每个 Tool 节点最大重试次数".into()),
            is_secret: false,
        },
        // ── 评分权重 ──
        Variable {
            name: "scoring_trend".into(),
            var_type: "number".into(),
            value: serde_json::json!(30.0),
            description: Some("趋势评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_deviation".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("偏离度评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_macd".into(),
            var_type: "number".into(),
            value: serde_json::json!(15.0),
            description: Some("MACD 评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_volume".into(),
            var_type: "number".into(),
            value: serde_json::json!(15.0),
            description: Some("成交量评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_rsi".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("RSI 评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_support".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("支撑阻力评分权重 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "scoring_boll".into(),
            var_type: "number".into(),
            value: serde_json::json!(5.0),
            description: Some("布林带评分权重 (0-100)".into()),
            is_secret: false,
        },
        // ── 规则引擎阈值 ──
        Variable {
            name: "rule_rsi_overbought".into(),
            var_type: "number".into(),
            value: serde_json::json!(80.0),
            description: Some("RSI 超买阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "rule_rsi_oversold".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("RSI 超卖阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "rule_bias_limit_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(5.0),
            description: Some("均线偏离极限 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "rule_volume_signal_block".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("成交量异常时是否阻塞信号".into()),
            is_secret: false,
        },
        Variable {
            name: "rule_bear_low_score".into(),
            var_type: "number".into(),
            value: serde_json::json!(30),
            description: Some("空方低分阈值 (低于此分数触发警告)".into()),
            is_secret: false,
        },
        Variable {
            name: "rule_auto_stop_loss_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(5.0),
            description: Some("自动止损线 (%)".into()),
            is_secret: false,
        },
        // ── 仓位限制 ──
        Variable {
            name: "pos_max_single_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("单只股票最大仓位占比 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "pos_max_total".into(),
            var_type: "number".into(),
            value: serde_json::json!(10),
            description: Some("最大持仓数量".into()),
            is_secret: false,
        },
        Variable {
            name: "pos_max_sector_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(40.0),
            description: Some("最大行业暴露占比 (%)".into()),
            is_secret: false,
        },
        // ── 估值参数（A股校准：详见 decision.rs::ValueConfig::default 注释）──
        Variable {
            name: "value_dcf_growth_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(12.0),
            description: Some("DCF 增长率 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "value_dcf_perpetual_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(4.0),
            description: Some("DCF 永续增长率 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "value_dcf_discount_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(8.5),
            description: Some("DCF 折现率 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "value_moat_threshold".into(),
            var_type: "number".into(),
            value: serde_json::json!(60),
            description: Some("护城河评分阈值 (0-100)".into()),
            is_secret: false,
        },
        Variable {
            name: "value_fscore_buy".into(),
            var_type: "number".into(),
            value: serde_json::json!(7),
            description: Some("F-Score 买入阈值 (0-9)".into()),
            is_secret: false,
        },
        Variable {
            name: "value_safety_margin".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("安全边际最低折扣 (%)".into()),
            is_secret: false,
        },
        // ── 监控参数 ──
        Variable {
            name: "monitor_poll_interval_secs".into(),
            var_type: "number".into(),
            value: serde_json::json!(30),
            description: Some("监控轮询间隔秒数".into()),
            is_secret: false,
        },
        Variable {
            name: "monitor_change_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(5.0),
            description: Some("价格异动提醒阈值 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "monitor_turnover".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("换手率异动提醒阈值 (%)".into()),
            is_secret: false,
        },
        // ── 置信度参数 ──
        Variable {
            name: "min_confidence".into(),
            var_type: "number".into(),
            value: serde_json::json!(60),
            description: Some("最低置信度阈值 (低于此值建议观望)".into()),
            is_secret: false,
        },
        // ── 数据源供应商开关 ──
        Variable {
            name: "vendor_tencent".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("腾讯财经 — 报价数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_eastmoney".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("东方财富 — 财务/K线数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_sina".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("新浪财经 — 新闻数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_ths".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("同花顺 — 综合数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_cninfo".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("巨潮资讯 — 信息披露".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_baidu_stock".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("百度股票 — 数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_iwencai".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("问财 — 选股数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_akshare".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("AKShare — 开源数据".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_mootdx".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("Mootdx — 本地行情接口".into()),
            is_secret: false,
        },
        // ── 需要 Token/Key 的数据源（开关默认关闭，需用户手动配置凭据后开启）──
        Variable {
            name: "vendor_xueqiu".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(false),
            description: Some("雪球 — 需配置 xq_a_token".into()),
            is_secret: false,
        },
        Variable {
            name: "vendor_neodata".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(false),
            description: Some("NeoData — 需配置 API Token".into()),
            is_secret: false,
        },
        // ── 凭据变量（is_secret=true，前端设置页管理）──
        // 后端 stock_analysis.rs / core.rs 通过变量名读取并注入到 vendor
        Variable {
            name: "vendor_iwencai_key".into(),
            var_type: "string".into(),
            value: serde_json::json!(""),
            description: Some("问财 API Key".into()),
            is_secret: true,
        },
        Variable {
            name: "vendor_xueqiu_token".into(),
            var_type: "string".into(),
            value: serde_json::json!(""),
            description: Some("雪球 xq_a_token".into()),
            is_secret: true,
        },
        Variable {
            name: "vendor_neodata_token".into(),
            var_type: "string".into(),
            value: serde_json::json!(""),
            description: Some("NeoData API Token".into()),
            is_secret: true,
        },
        // ── 金融模型参数 ──
        Variable {
            name: "risk_free_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.03),
            description: Some("无风险利率".into()),
            is_secret: false,
        },
        Variable {
            name: "var_confidence".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.95),
            description: Some("VaR 置信度 (0-1)".into()),
            is_secret: false,
        },
        Variable {
            name: "outlier_method".into(),
            var_type: "enum".into(),
            value: serde_json::json!("zscore"),
            description: Some("异常值检测方法: zscore / iqr".into()),
            is_secret: false,
        },
        Variable {
            name: "outlier_threshold".into(),
            var_type: "number".into(),
            value: serde_json::json!(2.0),
            description: Some("异常值 Z-score 阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_fraction".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.5),
            description: Some("凯利仓位系数".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_min_win_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.4),
            description: Some("凯利最低胜率要求 (0-1)".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_min_odds".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.0),
            description: Some("凯利最低赔率要求".into()),
            is_secret: false,
        },
        Variable {
            name: "cost_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.003),
            description: Some("交易成本率 (0.003=0.3%)".into()),
            is_secret: false,
        },
        // ── 金融模型补充参数 ──
        Variable {
            name: "risk_sharpe_annualization".into(),
            var_type: "number".into(),
            value: serde_json::json!(252),
            description: Some("夏普比率年化因子（交易日数）".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_kelly_heavy_threshold".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.25),
            description: Some("凯利重度仓位阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_kelly_medium_threshold".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.1),
            description: Some("凯利中度仓位阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_default_win_rate".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.5),
            description: Some("凯利默认胜率 (0-1)".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_default_avg_win".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.05),
            description: Some("凯利默认平均盈利率".into()),
            is_secret: false,
        },
        Variable {
            name: "kelly_default_avg_loss".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.05),
            description: Some("凯利默认平均亏损率".into()),
            is_secret: false,
        },
        // ── 组合风控 ──
        Variable {
            name: "risk_max_drawdown_limit".into(),
            var_type: "number".into(),
            value: serde_json::json!(15.0),
            description: Some("组合最大回撤熔断线 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_max_daily_loss_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(3.0),
            description: Some("单日最大亏损 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_correlation_lookback_days".into(),
            var_type: "number".into(),
            value: serde_json::json!(60),
            description: Some("相关性回看天数".into()),
            is_secret: false,
        },
        // ── 信号检测参数 ──
        Variable {
            name: "signal_rsi_oversold".into(),
            var_type: "number".into(),
            value: serde_json::json!(30.0),
            description: Some("RSI 超卖信号阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "signal_rsi_overbought".into(),
            var_type: "number".into(),
            value: serde_json::json!(70.0),
            description: Some("RSI 超买信号阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "signal_ma_fast".into(),
            var_type: "number".into(),
            value: serde_json::json!(5),
            description: Some("MA 金叉检测快线周期".into()),
            is_secret: false,
        },
        Variable {
            name: "signal_ma_slow".into(),
            var_type: "number".into(),
            value: serde_json::json!(20),
            description: Some("MA 金叉检测慢线周期".into()),
            is_secret: false,
        },
        Variable {
            name: "signal_breakout_volume_mult".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.5),
            description: Some("突破/破位放量倍数阈值".into()),
            is_secret: false,
        },
        // ── 关键价位参数 ──
        Variable {
            name: "keylevel_lookback_days".into(),
            var_type: "number".into(),
            value: serde_json::json!(60),
            description: Some("关键价位回看窗口 (交易日)".into()),
            is_secret: false,
        },
        Variable {
            name: "keylevel_touch_tolerance_pct".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.0),
            description: Some("关键价位触碰容差 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "keylevel_min_touches".into(),
            var_type: "number".into(),
            value: serde_json::json!(2),
            description: Some("确认支撑/阻力最少触碰次数".into()),
            is_secret: false,
        },
        // ── 监控告警参数 ──
        Variable {
            name: "monitor_alert_cooldown_secs".into(),
            var_type: "number".into(),
            value: serde_json::json!(300),
            description: Some("同一标的告警冷却时间 (秒)".into()),
            is_secret: false,
        },
        Variable {
            name: "monitor_min_severity".into(),
            var_type: "enum".into(),
            value: serde_json::json!("info"),
            description: Some("最低推送告警等级: info / warn / critical".into()),
            is_secret: false,
        },
        Variable {
            name: "monitor_channels".into(),
            var_type: "string".into(),
            value: serde_json::json!("in_app"),
            description: Some("推送渠道，逗号分隔: in_app / lark / email / webhook".into()),
            is_secret: false,
        },
        // ── 推荐器策略开关 ──
        Variable {
            name: "reco_trend_enabled".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("启用趋势跟踪子策略".into()),
            is_secret: false,
        },
        Variable {
            name: "reco_reversion_enabled".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("启用超跌反弹子策略".into()),
            is_secret: false,
        },
        Variable {
            name: "reco_value_enabled".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("启用价值选股子策略".into()),
            is_secret: false,
        },
        Variable {
            name: "reco_capital_enabled".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("启用资金流向子策略".into()),
            is_secret: false,
        },
        Variable {
            name: "reco_watchlist_enabled".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(true),
            description: Some("启用自选股策略".into()),
            is_secret: false,
        },
        Variable {
            name: "reco_min_confidence".into(),
            var_type: "number".into(),
            value: serde_json::json!(60),
            description: Some("推荐器最低置信度 (0-100)".into()),
            is_secret: false,
        },
        // ── 决策回溯参数 ──
        Variable {
            name: "decision_max_history_per_stock".into(),
            var_type: "number".into(),
            value: serde_json::json!(50),
            description: Some("每只股票保留的历史决策条数".into()),
            is_secret: false,
        },
        // ── 技术指标周期 ──
        Variable {
            name: "macd_fast".into(),
            var_type: "number".into(),
            value: serde_json::json!(12),
            description: Some("MACD 快线周期".into()),
            is_secret: false,
        },
        Variable {
            name: "macd_slow".into(),
            var_type: "number".into(),
            value: serde_json::json!(26),
            description: Some("MACD 慢线周期".into()),
            is_secret: false,
        },
        Variable {
            name: "macd_signal".into(),
            var_type: "number".into(),
            value: serde_json::json!(9),
            description: Some("MACD 信号线周期".into()),
            is_secret: false,
        },
        Variable {
            name: "boll_period".into(),
            var_type: "number".into(),
            value: serde_json::json!(20),
            description: Some("布林带周期".into()),
            is_secret: false,
        },
        Variable {
            name: "boll_stddev".into(),
            var_type: "number".into(),
            value: serde_json::json!(2.0),
            description: Some("布林带标准差倍数".into()),
            is_secret: false,
        },
        Variable {
            name: "volume_lookback".into(),
            var_type: "number".into(),
            value: serde_json::json!(5),
            description: Some("均量计算回看周期 (交易日)".into()),
            is_secret: false,
        },
        Variable {
            name: "volume_surge_ratio".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.5),
            description: Some("放量阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "volume_shrink_ratio".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.7),
            description: Some("缩量阈值".into()),
            is_secret: false,
        },
        // ── 技术指标补充参数 ──
        Variable {
            name: "atr_period".into(),
            var_type: "number".into(),
            value: serde_json::json!(14),
            description: Some("ATR 计算周期（默认 14）".into()),
            is_secret: false,
        },
        Variable {
            name: "kdj_n".into(),
            var_type: "number".into(),
            value: serde_json::json!(9),
            description: Some("KDJ 计算周期 N".into()),
            is_secret: false,
        },
        Variable {
            name: "fill_missing_method".into(),
            var_type: "enum".into(),
            value: serde_json::json!("forward"),
            description: Some("数据清洗缺失值填充: forward / zero / drop".into()),
            is_secret: false,
        },
        Variable {
            name: "breakout_volume_threshold".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.5),
            description: Some("突破放量倍数阈值".into()),
            is_secret: false,
        },
        // ── 推荐器策略参数 ──
        Variable {
            name: "trend_kline_limit".into(),
            var_type: "number".into(),
            value: serde_json::json!(250),
            description: Some("趋势策略读取 K 线上限".into()),
            is_secret: false,
        },
        Variable {
            name: "trend_amount_ratio_min".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.8),
            description: Some("趋势策略最低量比".into()),
            is_secret: false,
        },
        Variable {
            name: "rev_rsi_short_max".into(),
            var_type: "number".into(),
            value: serde_json::json!(35.0),
            description: Some("超跌反弹 RSI 判断上限".into()),
            is_secret: false,
        },
        // ── 基本面修正阈值 ──
        Variable {
            name: "val_pe_low".into(),
            var_type: "number".into(),
            value: serde_json::json!(15.0),
            description: Some("基本面修正 PE 低估阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "val_pe_high".into(),
            var_type: "number".into(),
            value: serde_json::json!(50.0),
            description: Some("基本面修正 PE 高估阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "val_pb_low".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.0),
            description: Some("基本面修正 PB 低估阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "val_pb_high".into(),
            var_type: "number".into(),
            value: serde_json::json!(6.0),
            description: Some("基本面修正 PB 高估阈值".into()),
            is_secret: false,
        },
        // ── 组合风控 HHI ──
        Variable {
            name: "risk_hhi_concentrated".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.25),
            description: Some("组合 HHI 高度集中阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_hhi_medium".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.15),
            description: Some("组合 HHI 中度集中阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_divers_high".into(),
            var_type: "number".into(),
            value: serde_json::json!(8.0),
            description: Some("组合有效股票数充分分散阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "risk_divers_medium".into(),
            var_type: "number".into(),
            value: serde_json::json!(4.0),
            description: Some("组合有效股票数适度分散阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "analysis_dry_run".into(),
            var_type: "boolean".into(),
            value: serde_json::json!(false),
            description: Some("干跑模式：不调用 LLM，用 mock 输出验证流程".into()),
            is_secret: false,
        },
        // ── 业绩超预期分级阈值 ──
        Variable {
            name: "earnings_th_huge_pos".into(),
            var_type: "number".into(),
            value: serde_json::json!(50.0),
            description: Some("大幅超预期下界 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "earnings_th_strong_pos".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("强超预期下界 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "earnings_th_mild_pos".into(),
            var_type: "number".into(),
            value: serde_json::json!(5.0),
            description: Some("略超预期下界 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "earnings_th_mild_neg".into(),
            var_type: "number".into(),
            value: serde_json::json!(-5.0),
            description: Some("略低于预期下界 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "earnings_th_strong_neg".into(),
            var_type: "number".into(),
            value: serde_json::json!(-20.0),
            description: Some("强低于预期下界 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "earnings_th_huge_neg".into(),
            var_type: "number".into(),
            value: serde_json::json!(-50.0),
            description: Some("大幅低于预期下界 (%)".into()),
            is_secret: false,
        },
        // ── 质押风险分级阈值 ──
        Variable {
            name: "pledge_warning_line".into(),
            var_type: "number".into(),
            value: serde_json::json!(50.0),
            description: Some("大股东质押比例预警线 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "pledge_liquidation_line".into(),
            var_type: "number".into(),
            value: serde_json::json!(70.0),
            description: Some("大股东质押比例平仓线 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "pledge_medium_line".into(),
            var_type: "number".into(),
            value: serde_json::json!(30.0),
            description: Some("大股东质押中风险阈值 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "pledge_low_line".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("大股东质押低风险阈值 (%)".into()),
            is_secret: false,
        },
        // ── 蒙特卡洛模拟默认参数 ──
        Variable {
            name: "mc_default_price".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("蒙特卡洛模拟默认价格".into()),
            is_secret: false,
        },
        Variable {
            name: "mc_default_return".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.08),
            description: Some("蒙特卡洛模拟默认年化收益".into()),
            is_secret: false,
        },
        Variable {
            name: "mc_default_volatility".into(),
            var_type: "number".into(),
            value: serde_json::json!(0.3),
            description: Some("蒙特卡洛模拟默认年化波动率".into()),
            is_secret: false,
        },
        Variable {
            name: "mc_default_days".into(),
            var_type: "number".into(),
            value: serde_json::json!(30),
            description: Some("蒙特卡洛模拟默认天数".into()),
            is_secret: false,
        },
        Variable {
            name: "mc_default_simulations".into(),
            var_type: "number".into(),
            value: serde_json::json!(1000),
            description: Some("蒙特卡洛模拟默认路径数".into()),
            is_secret: false,
        },
        // ── 行业内估值/增长对比阈值 ──
        Variable {
            name: "industry_pe_cheap".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.0),
            description: Some("行业内 PE 相对低估阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "industry_pe_expensive".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.5),
            description: Some("行业内 PE 相对高估阈值".into()),
            is_secret: false,
        },
        Variable {
            name: "industry_growth_high".into(),
            var_type: "number".into(),
            value: serde_json::json!(1.2),
            description: Some("行业内高增长阈值".into()),
            is_secret: false,
        },
        // ── 涨停潜力评分 ──
        Variable {
            name: "limit_pct_main".into(),
            var_type: "number".into(),
            value: serde_json::json!(10.0),
            description: Some("主板涨停幅度 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "limit_pct_star".into(),
            var_type: "number".into(),
            value: serde_json::json!(20.0),
            description: Some("创业板/科创板涨停幅度 (%)".into()),
            is_secret: false,
        },
        Variable {
            name: "limit_pct_bj".into(),
            var_type: "number".into(),
            value: serde_json::json!(30.0),
            description: Some("北交所涨停幅度 (%)".into()),
            is_secret: false,
        },
        // ── 反思复盘参数 ──
        Variable {
            name: "actual_outcome".into(),
            var_type: "string".into(),
            value: serde_json::json!(""),
            description: Some("实际走势结果，非空时切换反思模式".into()),
            is_secret: false,
        },
        Variable {
            name: "reflection_depth".into(),
            var_type: "string".into(),
            value: serde_json::json!("light"),
            description: Some("反思深度：light(简要) / deep(详细推理链)".into()),
            is_secret: false,
        },
        // ── 历史反思教训注入 ──
        Variable {
            name: "stock_lessons".into(),
            var_type: "string".into(),
            value: serde_json::json!("（暂无历史反思）"),
            description: Some("该股最近 90 天的反思教训,由 runtime 注入".into()),
            is_secret: false,
        },
    ]
}
