// 消息主题分组分隔条 — 折叠/展开，手动调整
import { useTopicGroupStore } from "@/stores/feature/topicGroupStore";
import type { TopicGroup } from "@/stores/feature/topicGroupStore";
import { Dropdown, Input, theme } from "antd";
import { ChevronDown, ChevronRight, Edit3, GitBranch, Trash2, X } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import "./TopicGroupDivider.css";

interface TopicGroupDividerProps {
  conversationId: string;
  group: TopicGroup;
}

export function TopicGroupDivider({ conversationId, group }: TopicGroupDividerProps) {
  const { t } = useTranslation();
  const { token } = theme.useToken();
  const toggleCollapse = useTopicGroupStore((s) => s.toggleCollapse);
  const renameGroup = useTopicGroupStore((s) => s.renameGroup);
  const deleteGroup = useTopicGroupStore((s) => s.deleteGroup);
  const mergeUp = useTopicGroupStore((s) => s.mergeUp);
  const [editing, setEditing] = useState(false);
  const [label, setLabel] = useState(group.label);

  const handleRename = () => {
    if (label.trim()) { renameGroup(conversationId, group.id, label.trim()); }
    setEditing(false);
  };

  const menuItems = {
    items: [
      { key: "rename", label: t("topicGroup.rename", "重命名"), icon: <Edit3 size={12} /> },
      { key: "merge", label: t("topicGroup.mergeUp", "合并到上一组"), icon: <GitBranch size={12} /> },
      { key: "delete", label: t("topicGroup.delete", "删除分组"), icon: <Trash2 size={12} />, danger: true },
    ],
    onClick: ({ key }: { key: string }) => {
      switch (key) {
        case "rename":
          setLabel(group.label);
          setEditing(true);
          break;
        case "merge":
          mergeUp(conversationId, group.id);
          break;
        case "delete":
          deleteGroup(conversationId, group.id);
          break;
      }
    },
  };

  return (
    <div className="topic-group-divider" style={{ borderColor: token.colorBorderSecondary }}>
      <Dropdown menu={menuItems} trigger={["contextMenu"]}>
        <div
          className="topic-group-divider__bar"
          onClick={() => toggleCollapse(conversationId, group.id)}
          style={{
            display: "flex",
            alignItems: "center",
            gap: 6,
            padding: "6px 16px",
            cursor: "pointer",
            backgroundColor: token.colorFillQuaternary,
            borderRadius: 4,
            margin: "4px 0",
          }}
        >
          {group.collapsed
            ? <ChevronRight size={12} style={{ color: token.colorTextQuaternary }} />
            : <ChevronDown size={12} style={{ color: token.colorTextQuaternary }} />}
          {editing
            ? (
              <Input
                id="topic-group-divider-input-33"
                size="small"
                value={label}
                onChange={(e) => setLabel(e.target.value)}
                onBlur={handleRename}
                onPressEnter={handleRename}
                style={{ flex: 1, height: 22, fontSize: 12 }}
                onClick={(e) => e.stopPropagation()}
              />
            )
            : (
              <span
                style={{
                  fontSize: 12,
                  fontWeight: 500,
                  color: group.autoGenerated ? token.colorTextSecondary : token.colorText,
                  flex: 1,
                }}
              >
                {group.autoGenerated ? "📌 " : ""}
                {group.label}
              </span>
            )}
          <span style={{ fontSize: 11, color: token.colorTextQuaternary }}>
            {group.messageIds.length}
          </span>
          {group.collapsed && (
            <span style={{ fontSize: 10, color: token.colorTextQuaternary }}>
              {t("topicGroup.collapsed", "已折叠")}
            </span>
          )}
          {editing && (
            <X
              size={12}
              style={{ cursor: "pointer", color: token.colorTextQuaternary }}
              onClick={(e) => {
                e.stopPropagation();
                setEditing(false);
              }}
            />
          )}
        </div>
      </Dropdown>
    </div>
  );
}
