// SPDX-License-Identifier: AGPL-3.0-only

export type AgentBehaviorMode = "default" | "accept_edits" | "full_access";
export type AgentRuntimeStatus =
  | "idle"
  | "running"
  | "waiting_approval"
  | "completed"
  | "error";
export type ApprovalStatus = "pending" | "approved" | "denied";

export interface AgentSession {
  id: string;
  conversationId: string;
  cwd?: string;
  workspaceLocked?: boolean;
  permissionMode: AgentBehaviorMode;
  runtimeStatus: AgentRuntimeStatus;
  totalTokens: number;
  totalCostUsd: number;
}

// --- Event payload types (all tool-related events carry assistantMessageId anchor) ---

export interface ToolUseEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  executionId?: string;
}

export interface ToolStartEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  /** Server-side timestamp (ms since epoch) when tool execution began */
  startedAt?: number;
  /** Current iteration / total iterations at time of tool start */
  iteration?: number;
  maxIterations?: number;
}

export interface ToolResultEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  content: string;
  isError: boolean;
  input?: Record<string, unknown>;
  /** Server-side timestamp (ms since epoch) when tool execution began */
  startedAt?: number;
}

export interface PermissionRequestEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  riskLevel: "read_only" | "write" | "execute";
  /** The request_id generated by ChannelPermissionPrompter, used to reply via agent_approve */
  requestId: string;
}

export interface PlanApprovalEvent {
  conversationId: string;
  /** JSON 字符串，由后端 build_plan_draft_content 生成的计划草稿 */
  plan: string;
}

export interface AskUserEvent {
  conversationId: string;
  assistantMessageId: string;
  askId: string;
  question: string;
  options?: string[];
}

export interface AgentDoneEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
  thinking?: string;
  usage?: { inputTokens: number; outputTokens: number };
  numTurns?: number;
  costUsd?: number;
  blocks?: Array<{
    type: "text" | "tool_use" | "tool_result";
    text?: string;
    id?: string;
    name?: string;
    input?: string;
    toolUseId?: string;
    toolName?: string;
    output?: string;
    isError?: boolean;
  }>;
}

export interface AgentErrorEvent {
  conversationId: string;
  assistantMessageId?: string;
  message: string;
}

export interface AgentCancelledEvent {
  conversationId: string;
  assistantMessageId?: string;
  reason: string;
}

/** Emitted when a model fails and the system falls back to an alternate model. */
export interface ModelFallbackEvent {
  conversationId: string;
  /** The model that failed. */
  fromProviderId: string;
  fromModelId: string;
  /** The model that was selected as fallback. */
  toProviderId: string;
  toModelId: string;
  /** Why the original model failed (e.g. "rate_limited", "connection_refused", "timeout"). */
  reason: string;
  /** Whether this was the final fallback (no more models to try). */
  exhausted: boolean;
}

export interface AgentStatusEvent {
  conversationId: string;
  phase?: string;
  message: string;
  /** Current loop iteration (1-based) */
  iteration?: number;
  /** Maximum iterations allowed */
  totalIterations?: number;
  /** Name of the currently executing tool, if any */
  currentTool?: string;
  /** Total tools executed so far */
  executedToolCount?: number;
  /** Number of failed tools */
  failedToolCount?: number;
  /** Latest error message, if any */
  lastError?: string;
  /** Human-readable status description */
  statusMessage?: string;
}

export interface AgentRateLimitEvent {
  conversationId: string;
  retryAfterMs: number;
  message: string;
}

export interface AgentStreamTextEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
}

export interface AgentStreamThinkingEvent {
  conversationId: string;
  assistantMessageId: string;
  thinking: string;
}

export interface WorkflowStepStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_start";
  stepId: string;
  stepGoal: string;
  agentRole: string;
}

export interface WorkflowStepCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_complete";
  stepId: string;
  stepGoal: string;
  result: string;
}

export interface WorkflowStepErrorEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_error";
  stepId: string;
  error: string;
}

export interface WorkflowStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_start";
  workflowId: string;
}

export interface WorkflowCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  workflowId: string;
  success: boolean;
}

export interface WorkflowHeartbeatEvent {
  type: "workflow_heartbeat";
  conversationId?: string;
  assistantMessageId?: string;
  workflowId: string;
  nodeId: string;
  elapsedMs: number;
  heartbeatCount: number;
  timeoutMs?: number;
  emittedAtMs: number;
}

export interface WorkflowTimeoutWarningEvent {
  type: "workflow_timeout_warning";
  conversationId?: string;
  assistantMessageId?: string;
  workflowId: string;
  nodeId: string;
  elapsedMs: number;
  timeoutMs: number;
  remainingMs?: number;
  level: "warning" | "critical";
  emittedAtMs: number;
}

export type WorkflowEvent =
  | WorkflowStepStartEvent
  | WorkflowStepCompleteEvent
  | WorkflowStepErrorEvent
  | WorkflowStartEvent
  | WorkflowHeartbeatEvent
  | WorkflowTimeoutWarningEvent;

// --- Frontend runtime state ---

export interface ToolCallState {
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  assistantMessageId: string;
  executionStatus: "queued" | "running" | "success" | "failed" | "cancelled";
  approvalStatus?: ApprovalStatus;
  output?: string;
  isError?: boolean;
  startedAt?: number;
}

// --- Sub-agent card event ---

export interface SubAgentCardEvent {
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
  /** 是否为 fork 子 agent（继承父 agent 上下文） */
  isFork?: boolean;
}

export interface SubAgentCardData {
  id: string; // unique card ID (childConversationId)
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
  isFork?: boolean;
}

// ---------------------------------------------------------------------------
// 统一 AgentPool — 子Agent + 工作者 + 工作流步骤
// ---------------------------------------------------------------------------

/** AgentPool 中的条目类型 */
export type AgentPoolItemType = "sub_agent" | "worker" | "workflow_step";

/** AgentPool 中的条目状态 */
export type AgentPoolItemStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

/** Swarm 队友实时状态 */
export type TeammateStatus = "idle" | "busy" | "offline" | "error";

/** 工作者消息类型 */
export type WorkerMessageType = "progress" | "result" | "error" | "completion";

/** 工作者发送给协调者的消息 */
export interface WorkerMessage {
  workerId: string;
  taskId: string;
  messageType: WorkerMessageType;
  content: string;
  metadata?: Record<string, unknown>;
  timestamp?: number;
}

/** 统一的 AgentPool 条目 */
export interface AgentPoolItem {
  id: string;
  conversationId: string;
  type: AgentPoolItemType;
  name: string;
  status: AgentPoolItemStatus;
  /** 进度 0-100（workflow_step 和 worker 使用） */
  progress?: number;
  /** 状态摘要文本 */
  summary?: string;
  /** 错误信息 */
  error?: string;
  /** 依赖的前置任务 ID 列表 */
  dependsOn?: string[];
  /** 开始时间（毫秒时间戳） */
  startedAt?: number;
  /** 持续时间（毫秒） */
  duration?: number;

  // -- sub_agent 专用 --
  agentType?: string;
  childConversationId?: string;
  childSessionId?: string;
  /** 是否为 fork 子 agent */
  isFork?: boolean;
  /** 关联的消息 ID，用于点击跳转到对话中的消息 */
  messageId?: string;

  // -- 队友面板专用 --
  /** 队友当前正在执行的任务描述 */
  currentTask?: string;
  /** 所属团队名称（Swarm 编队） */
  teamName?: string;

  // -- worker 专用 --
  taskDescription?: string;
  messages?: WorkerMessage[];

  // -- workflow_step 专用 --
  stepIndex?: number;
  agentRole?: string;
  maxRetries?: number;
  attempts?: number;
  onFailure?: "abort" | "skip";
  canRetry?: boolean;
}

/** AgentPool 汇总统计 */
export interface AgentPoolSummary {
  total: number;
  completed: number;
  running: number;
  pending: number;
  failed: number;
  pctComplete: number; // 0-100
}

// ── SubAgent 注册类型（对应后端 trajectory::SubAgent）──

export type SubAgentStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

export interface SubAgentMetadata {
  agentType: string;
  capabilities: string[];
  model?: string;
  tools: string[];
}

export interface SubAgent {
  id: string;
  parentId?: string;
  name: string;
  description: string;
  status: SubAgentStatus;
  task?: string;
  progress: number;
  result?: string;
  error?: string;
  createdAt: string;
  completedAt?: string;
  children: string[];
  metadata: SubAgentMetadata;
}

// ── Trajectory 轨迹类型 ──

export interface TrajectorySummary {
  id: string;
  sessionId: string;
  /** 结构化 agent 标识：记录该轨迹由哪个 Agent（AgentProfile 名称）执行 */
  agentName?: string;
  topic: string;
  outcome: string;
  durationMs: number;
  quality?: {
    overall: number;
    taskCompletion: number;
    toolEfficiency: number;
    reasoningQuality: number;
    userSatisfaction: number;
  };
  stepCount: number;
  createdAt: string;
}

export interface TrajectoryStep {
  timestampMs: number;
  role: string;
  content: string;
  reasoning?: string;
  toolCalls?: Array<{
    id: string;
    name: string;
    input: Record<string, unknown>;
  }>;
  toolResults?: Array<{
    id: string;
    output: string;
    error?: string;
  }>;
}

export interface TrajectoryDetail {
  id: string;
  sessionId: string;
  /** 结构化 agent 标识：记录该轨迹由哪个 Agent（AgentProfile 名称）执行 */
  agentName?: string;
  topic: string;
  outcome: string;
  durationMs: number;
  quality?: {
    overall: number;
    taskCompletion: number;
    toolEfficiency: number;
    reasoningQuality: number;
    userSatisfaction: number;
  };
  steps: TrajectoryStep[];
  patterns: string[];
  rewards: Array<{
    rewardType: string;
    value: number;
    stepIndex: number;
    timestampMs: number;
  }>;
  createdAt: string;
  replayCount: number;
}

/** 智能体模式枚举 */
export type AgentPatternType =
  | "react"
  | "plan-and-execute"
  | "reflection"
  | "multi-agent"
  | "code-review"
  | "data-analysis"
  | "document-processing"
  | "web-research"
  | "custom";

/** 模式复杂度等级 */
export type PatternComplexity = "low" | "medium" | "high" | "expert";

/** 智能体模式模板 */
export interface AgentPattern {
  id: string;
  type: AgentPatternType;
  name: string;
  description: string;
  complexity: PatternComplexity;
  triggerKeywords: string[];
  systemPromptTemplate: string;
  availableTools: string[];
  requiredCapabilities: string[];
  maxTurns: number;
  estimatedTokenRange: { min: number; max: number };
  isBuiltin: boolean;
  version: string;
}

/** 模式匹配结果 */
export interface PatternMatchResult {
  pattern: AgentPattern;
  confidence: number;
  matchedKeywords: string[];
  reasoning: string;
}

// ============================================================================
// AgentSessionBroker DTOs (后端 harness AgentSessionStatusView 镜像, camelCase 对齐)
// ============================================================================

/** Agent 会话状态枚举 (后端 SessionStatus snake_case 序列化值) */
export type AgentSessionStatus =
  | "idle"
  | "initializing"
  | "running"
  | "waiting_approval"
  | "paused"
  | "completed"
  | "failed"
  | "cancelled";

/** Agent 会话状态视图 (后端 harness AgentSessionBroker::get_session_status 返回值) */
export interface AgentSessionStatusView {
  /** 会话唯一 ID */
  sessionId: string;
  /** 当前状态 (8 态状态机) */
  status: AgentSessionStatus;
  /** 关联的 LLM provider 标识 */
  providerId: string;
  /** 关联的 conversation_id (可能为空) */
  conversationId?: string;
  /** 已完成的 turn 数 */
  turnCount?: number;
  /** 是否活跃 (idle/initializing/running/waiting_approval/paused) */
  isActive: boolean;
  /** 最近访问时间戳 epoch ms */
  lastAccessMs?: number;
  /** 最近错误信息 */
  lastError?: string;
}
