export type AgentPermissionMode = "default" | "accept_edits" | "full_access";
export type AgentRuntimeStatus = "idle" | "running" | "waiting_approval" | "completed" | "error";
export type ApprovalStatus = "pending" | "approved" | "denied";

export interface AgentSession {
  id: string;
  conversation_id: string;
  cwd?: string;
  workspace_locked?: boolean;
  permission_mode: AgentPermissionMode;
  runtime_status: AgentRuntimeStatus;
  total_tokens: number;
  total_cost_usd: number;
}

// --- Event payload types (all tool-related events carry assistantMessageId anchor) ---

export interface ToolUseEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  executionId?: string;
}

export interface ToolStartEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
}

export interface ToolResultEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  content: string;
  isError: boolean;
}

export interface PermissionRequestEvent {
  conversationId: string;
  assistantMessageId: string;
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  riskLevel: "read_only" | "write" | "execute";
  /** The request_id generated by ChannelPermissionPrompter, used to reply via agent_approve */
  requestId: string;
}

export interface AskUserEvent {
  conversationId: string;
  assistantMessageId: string;
  askId: string;
  question: string;
  options?: string[];
}

export interface AgentDoneEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
  thinking?: string;
  usage?: { input_tokens: number; output_tokens: number };
  numTurns?: number;
  costUsd?: number;
  blocks?: Array<{
    type: "text" | "tool_use" | "tool_result";
    text?: string;
    id?: string;
    name?: string;
    input?: string;
    toolUseId?: string;
    toolName?: string;
    output?: string;
    isError?: boolean;
  }>;
}

export interface AgentErrorEvent {
  conversationId: string;
  assistantMessageId?: string;
  message: string;
}

export interface AgentCancelledEvent {
  conversationId: string;
  assistantMessageId?: string;
  reason: string;
}

/** Emitted when a model fails and the system falls back to an alternate model. */
export interface ModelFallbackEvent {
  conversationId: string;
  /** The model that failed. */
  fromProviderId: string;
  fromModelId: string;
  /** The model that was selected as fallback. */
  toProviderId: string;
  toModelId: string;
  /** Why the original model failed (e.g. "rate_limited", "connection_refused", "timeout"). */
  reason: string;
  /** Whether this was the final fallback (no more models to try). */
  exhausted: boolean;
}

export interface AgentStatusEvent {
  conversationId: string;
  message: string;
}

export interface AgentRateLimitEvent {
  conversationId: string;
  retryAfterMs: number;
  message: string;
}

export interface AgentStreamTextEvent {
  conversationId: string;
  assistantMessageId: string;
  text: string;
}

export interface AgentStreamThinkingEvent {
  conversationId: string;
  assistantMessageId: string;
  thinking: string;
}

export interface WorkflowStepStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_start";
  stepId: string;
  stepGoal: string;
  agentRole: string;
}

export interface WorkflowStepCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_complete";
  stepId: string;
  stepGoal: string;
  result: string;
}

export interface WorkflowStepErrorEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_step_error";
  stepId: string;
  error: string;
}

export interface WorkflowStartEvent {
  conversationId: string;
  assistantMessageId: string;
  type: "workflow_start";
  workflowId: string;
}

export interface WorkflowCompleteEvent {
  conversationId: string;
  assistantMessageId: string;
  workflowId: string;
  success: boolean;
}

export type WorkflowEvent =
  | WorkflowStepStartEvent
  | WorkflowStepCompleteEvent
  | WorkflowStepErrorEvent
  | WorkflowStartEvent;

// --- Frontend runtime state ---

export interface ToolCallState {
  toolUseId: string;
  toolName: string;
  input: Record<string, unknown>;
  assistantMessageId: string;
  executionStatus: "queued" | "running" | "success" | "failed" | "cancelled";
  approvalStatus?: ApprovalStatus;
  output?: string;
  isError?: boolean;
}

// --- Sub-agent card event ---

export interface SubAgentCardEvent {
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
  /** 是否为 fork 子 agent（继承父 agent 上下文） */
  isFork?: boolean;
}

export interface SubAgentCardData {
  id: string; // unique card ID (childConversationId)
  conversationId: string;
  agentType: string;
  agentName: string;
  description: string;
  status: "running" | "completed" | "failed";
  childConversationId?: string;
  childSessionId?: string;
  isFork?: boolean;
}

// ---------------------------------------------------------------------------
// 统一 AgentPool — 子Agent + 工作者 + 工作流步骤
// ---------------------------------------------------------------------------

/** AgentPool 中的条目类型 */
export type AgentPoolItemType = "sub_agent" | "worker" | "workflow_step";

/** AgentPool 中的条目状态 */
export type AgentPoolItemStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed"
  | "cancelled";

/** Swarm 队友实时状态 */
export type TeammateStatus = "idle" | "busy" | "offline" | "error";

/** 工作者消息类型 */
export type WorkerMessageType = "progress" | "result" | "error" | "completion";

/** 工作者发送给协调者的消息 */
export interface WorkerMessage {
  workerId: string;
  taskId: string;
  messageType: WorkerMessageType;
  content: string;
  metadata?: Record<string, unknown>;
  timestamp?: number;
}

/** 统一的 AgentPool 条目 */
export interface AgentPoolItem {
  id: string;
  conversationId: string;
  type: AgentPoolItemType;
  name: string;
  status: AgentPoolItemStatus;
  /** 进度 0-100（workflow_step 和 worker 使用） */
  progress?: number;
  /** 状态摘要文本 */
  summary?: string;
  /** 错误信息 */
  error?: string;
  /** 依赖的前置任务 ID 列表 */
  dependsOn?: string[];
  /** 开始时间（毫秒时间戳） */
  startedAt?: number;
  /** 持续时间（毫秒） */
  duration?: number;

  // -- sub_agent 专用 --
  agentType?: string;
  childConversationId?: string;
  childSessionId?: string;
  /** 是否为 fork 子 agent */
  isFork?: boolean;

  // -- 队友面板专用 --
  /** 队友当前正在执行的任务描述 */
  currentTask?: string;
  /** 所属团队名称（Swarm 编队） */
  teamName?: string;

  // -- worker 专用 --
  taskDescription?: string;
  messages?: WorkerMessage[];

  // -- workflow_step 专用 --
  stepIndex?: number;
  agentRole?: string;
  maxRetries?: number;
  attempts?: number;
  onFailure?: "abort" | "skip";
  canRetry?: boolean;
}

/** AgentPool 汇总统计 */
export interface AgentPoolSummary {
  total: number;
  completed: number;
  running: number;
  pending: number;
  failed: number;
  pctComplete: number; // 0-100
}

// ── SubAgent 注册类型（对应后端 trajectory::SubAgent）──

export type SubAgentStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

export interface SubAgentMetadata {
  agent_type: string;
  capabilities: string[];
  model?: string;
  tools: string[];
}

export interface SubAgent {
  id: string;
  parent_id?: string;
  name: string;
  description: string;
  status: SubAgentStatus;
  task?: string;
  progress: number;
  result?: string;
  error?: string;
  created_at: string;
  completed_at?: string;
  children: string[];
  metadata: SubAgentMetadata;
}
