// SPDX-License-Identifier: AGPL-3.0-only
//! 全量 schema 合规性测试。
//!
//! 验证所有 89 个 SeaORM 实体的每一列在 SQLite 内存库中运行全部迁移后真实存在。
//! 这是「字段缺失」bug 的回归防线。

use sea_orm::{ConnectionTrait, Database, DbBackend, Statement};

/// 完整 schema 定义：(表名, [(列名, 类型)])
/// 类型列仅作文档参考，实际检查只搜列名是否存在。
const SCHEMA: &[(&str, &[(&str, &str)])] = &[
    (
        "agency_experts",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("category", "TEXT"),
            ("system_prompt", "TEXT"),
            ("color", "TEXT"),
            ("source_dir", "TEXT"),
            ("is_enabled", "INTEGER"),
            ("imported_at", "BIGINT"),
            ("recommended_workflows", "TEXT"),
            ("recommended_tools", "TEXT"),
            ("active_domains", "TEXT"),
            ("seniority", "TEXT"),
            ("specialties", "TEXT"),
            ("parent_role_id", "TEXT"),
            ("success_rate", "REAL"),
            ("avg_latency_ms", "BIGINT"),
            ("avg_token_cost", "BIGINT"),
        ],
    ),
    (
        "agent_profiles",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("category", "TEXT"),
            ("icon", "TEXT"),
            ("agent_role", "TEXT"),
            ("source", "TEXT"),
            ("tags", "TEXT"),
            ("suggested_provider_id", "TEXT"),
            ("suggested_model_id", "TEXT"),
            ("suggested_temperature", "REAL"),
            ("suggested_max_tokens", "BIGINT"),
            ("search_enabled", "INTEGER"),
            ("recommend_permission_mode", "TEXT"),
            ("recommended_tools", "TEXT"),
            ("disallowed_tools", "TEXT"),
            ("recommended_workflows", "TEXT"),
            ("sort_order", "INTEGER"),
            ("is_enabled", "INTEGER"),
            ("expert_id", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "agent_roles",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("system_prompt", "TEXT"),
            ("default_tools", "TEXT"),
            ("active_domains", "TEXT"),
            ("max_concurrent", "INTEGER"),
            ("timeout_seconds", "BIGINT"),
            ("source", "TEXT"),
            ("sort_order", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("responsibilities", "TEXT"),
            ("decision_authority", "TEXT"),
            ("reports_to", "TEXT"),
            ("managed_expert_ids", "TEXT"),
            ("required_certifications", "TEXT"),
            ("icon", "TEXT"),
            ("color", "TEXT"),
            ("is_enabled", "INTEGER"),
        ],
    ),
    (
        "agent_sessions",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("cwd", "TEXT"),
            ("workspace_locked", "INTEGER"),
            ("permission_mode", "TEXT"),
            ("runtime_status", "TEXT"),
            ("sdk_context_json", "TEXT"),
            ("sdk_context_backup_json", "TEXT"),
            ("total_tokens", "BIGINT"),
            ("total_cost_usd", "REAL"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "artifacts",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("kind", "TEXT"),
            ("title", "TEXT"),
            ("content", "TEXT"),
            ("format", "TEXT"),
            ("pinned", "INTEGER"),
            ("updated_at", "TEXT"),
        ],
    ),
    (
        "background_tasks",
        &[
            ("id", "TEXT"),
            ("title", "TEXT"),
            ("description", "TEXT"),
            ("task_type", "TEXT"),
            ("command", "TEXT"),
            ("prompt", "TEXT"),
            ("status", "TEXT"),
            ("output", "TEXT"),
            ("exit_code", "INTEGER"),
            ("conversation_id", "TEXT"),
            ("created_by", "TEXT"),
            ("idempotency_key", "TEXT"),
            ("attempt", "INTEGER"),
            ("resume_from", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("finished_at", "BIGINT"),
        ],
    ),
    (
        "backup_manifests",
        &[
            ("id", "TEXT"),
            ("version", "TEXT"),
            ("created_at", "TEXT"),
            ("encrypted", "INTEGER"),
            ("checksum", "TEXT"),
            ("object_counts_json", "TEXT"),
            ("source_app_version", "TEXT"),
            ("file_path", "TEXT"),
            ("file_size", "BIGINT"),
        ],
    ),
    ("backup_targets", &[("id", "TEXT"), ("kind", "TEXT"), ("config_json", "TEXT")]),
    (
        "context_sources",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("message_id", "TEXT"),
            ("source_type", "TEXT"),
            ("ref_id", "TEXT"),
            ("title", "TEXT"),
            ("enabled", "INTEGER"),
            ("summary", "TEXT"),
            ("doc_ids_json", "TEXT"),
        ],
    ),
    (
        "conversation_branches",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("parent_message_id", "TEXT"),
            ("branch_label", "TEXT"),
            ("branch_index", "INTEGER"),
            ("compared_message_ids_json", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "conversation_categories",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("icon_type", "TEXT"),
            ("icon_value", "TEXT"),
            ("system_prompt", "TEXT"),
            ("default_provider_id", "TEXT"),
            ("default_model_id", "TEXT"),
            ("default_temperature", "REAL"),
            ("default_max_tokens", "BIGINT"),
            ("default_top_p", "REAL"),
            ("default_frequency_penalty", "REAL"),
            ("sort_order", "INTEGER"),
            ("is_collapsed", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "conversation_summaries",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("summary_text", "TEXT"),
            ("compressed_until_message_id", "TEXT"),
            ("token_count", "BIGINT"),
            ("model_used", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "conversations",
        &[
            ("id", "TEXT"),
            ("title", "TEXT"),
            ("model_id", "TEXT"),
            ("provider_id", "TEXT"),
            ("system_prompt", "TEXT"),
            ("temperature", "REAL"),
            ("max_tokens", "BIGINT"),
            ("top_p", "REAL"),
            ("frequency_penalty", "REAL"),
            ("search_enabled", "INTEGER"),
            ("search_provider_id", "TEXT"),
            ("thinking_budget", "BIGINT"),
            ("enabled_mcp_server_ids", "TEXT"),
            ("enabled_knowledge_base_ids", "TEXT"),
            ("enabled_memory_namespace_ids", "TEXT"),
            ("enabled_wiki_ids", "TEXT"),
            ("message_count", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("is_pinned", "INTEGER"),
            ("is_archived", "INTEGER"),
            ("workspace_snapshot_json", "TEXT"),
            ("active_branch_id", "TEXT"),
            ("active_artifact_id", "TEXT"),
            ("research_mode", "INTEGER"),
            ("context_compression", "INTEGER"),
            ("category_id", "TEXT"),
            ("parent_conversation_id", "TEXT"),
            ("mode", "TEXT"),
            ("work_strategy", "TEXT"),
            ("scenario", "TEXT"),
            ("enabled_skill_ids", "TEXT"),
            ("agent_profile_id", "TEXT"),
            ("workflow_template_id", "TEXT"),
            ("session_type", "TEXT"),
            ("workflow_status", "TEXT"),
            ("memory_status", "TEXT"),
            ("last_memory_extracted_at", "TEXT"),
        ],
    ),
    (
        "credentials",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("credential_type", "TEXT"),
            ("data_encrypted", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "desktop_state",
        &[
            ("window_key", "TEXT"),
            ("width", "INTEGER"),
            ("height", "INTEGER"),
            ("x", "BIGINT"),
            ("y", "BIGINT"),
            ("maximized", "INTEGER"),
            ("visible", "INTEGER"),
        ],
    ),
    (
        "dynamic_ui_form_data",
        &[
            ("id", "TEXT"),
            ("schema_id", "TEXT"),
            ("form_data_json", "TEXT"),
            ("instance_key", "TEXT"),
            ("updated_at", "TEXT"),
        ],
    ),
    (
        "dynamic_ui_pins",
        &[
            ("schema_id", "TEXT"),
            ("title", "TEXT"),
            ("group_name", "TEXT"),
            ("position", "INTEGER"),
            ("created_at", "TEXT"),
            ("updated_at", "TEXT"),
        ],
    ),
    (
        "dynamic_ui_schema_versions",
        &[
            ("id", "BIGINT"),
            ("schema_id", "TEXT"),
            ("version", "TEXT"),
            ("title", "TEXT"),
            ("description", "TEXT"),
            ("schema_json", "TEXT"),
            ("category", "TEXT"),
            ("tags", "TEXT"),
            ("change_log", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "dynamic_ui_schemas",
        &[
            ("id", "TEXT"),
            ("title", "TEXT"),
            ("description", "TEXT"),
            ("schema_json", "TEXT"),
            ("category", "TEXT"),
            ("tags", "TEXT"),
            ("version", "TEXT"),
            ("is_builtin", "INTEGER"),
            ("created_at", "TEXT"),
            ("updated_at", "TEXT"),
        ],
    ),
    (
        "fleet_members",
        &[
            ("id", "TEXT"),
            ("fleet_id", "TEXT"),
            ("agent_id", "TEXT"),
            ("agent_slug", "TEXT"),
            ("display_name", "TEXT"),
            ("role", "TEXT"),
            ("agent_profile_id", "TEXT"),
            ("room_id", "TEXT"),
            ("status", "TEXT"),
            ("joined_at", "BIGINT"),
            ("today_tokens", "BIGINT"),
            ("total_tokens", "BIGINT"),
        ],
    ),
    (
        "fleets",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("scene_template_slug", "TEXT"),
            ("status", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("metadata_json", "TEXT"),
        ],
    ),
    (
        "gateway_diagnostics",
        &[
            ("id", "TEXT"),
            ("category", "TEXT"),
            ("status", "TEXT"),
            ("message", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "gateway_keys",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("key_hash", "TEXT"),
            ("key_prefix", "TEXT"),
            ("enabled", "INTEGER"),
            ("created_at", "BIGINT"),
            ("last_used_at", "BIGINT"),
            ("encrypted_key", "TEXT"),
        ],
    ),
    (
        "gateway_link_activities",
        &[
            ("id", "TEXT"),
            ("link_id", "TEXT"),
            ("activity_type", "TEXT"),
            ("description", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "gateway_link_policies",
        &[
            ("id", "TEXT"),
            ("link_id", "TEXT"),
            ("route_strategy", "TEXT"),
            ("model_fallback_enabled", "INTEGER"),
            ("global_rpm", "BIGINT"),
            ("per_model_rpm", "BIGINT"),
            ("token_limit_per_minute", "BIGINT"),
            ("key_rotation_strategy", "TEXT"),
            ("key_failover_enabled", "INTEGER"),
        ],
    ),
    (
        "gateway_links",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("link_type", "TEXT"),
            ("endpoint", "TEXT"),
            ("api_key_id", "TEXT"),
            ("enabled", "INTEGER"),
            ("status", "TEXT"),
            ("error_message", "TEXT"),
            ("auto_sync_models", "INTEGER"),
            ("auto_sync_skills", "INTEGER"),
            ("last_sync_at", "BIGINT"),
            ("latency_ms", "BIGINT"),
            ("version", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "gateway_request_logs",
        &[
            ("id", "TEXT"),
            ("key_id", "TEXT"),
            ("key_name", "TEXT"),
            ("method", "TEXT"),
            ("path", "TEXT"),
            ("model", "TEXT"),
            ("provider_id", "TEXT"),
            ("status_code", "INTEGER"),
            ("duration_ms", "BIGINT"),
            ("request_tokens", "BIGINT"),
            ("response_tokens", "BIGINT"),
            ("error_message", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "gateway_usage",
        &[
            ("id", "BIGINT"),
            ("key_id", "TEXT"),
            ("provider_id", "TEXT"),
            ("model_id", "TEXT"),
            ("request_tokens", "BIGINT"),
            ("response_tokens", "BIGINT"),
            ("cached_input_tokens", "BIGINT"),
            ("cost", "REAL"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "generated_tools",
        &[
            ("id", "TEXT"),
            ("tool_name", "TEXT"),
            ("original_name", "TEXT"),
            ("original_description", "TEXT"),
            ("input_schema", "TEXT"),
            ("output_schema", "TEXT"),
            ("implementation", "TEXT"),
            ("source_info", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "import_jobs",
        &[
            ("id", "TEXT"),
            ("source_type", "TEXT"),
            ("status", "TEXT"),
            ("summary_json", "TEXT"),
            ("conflict_count", "INTEGER"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "index_jobs",
        &[
            ("id", "TEXT"),
            ("job_type", "TEXT"),
            ("container_type", "TEXT"),
            ("container_id", "TEXT"),
            ("item_id", "TEXT"),
            ("status", "TEXT"),
            ("current_stage", "TEXT"),
            ("progress", "INTEGER"),
            ("error_message", "TEXT"),
            ("retry_count", "INTEGER"),
            ("max_retries", "INTEGER"),
            ("priority", "INTEGER"),
            ("created_at", "BIGINT"),
            ("started_at", "BIGINT"),
            ("completed_at", "BIGINT"),
            ("metadata", "TEXT"),
        ],
    ),
    (
        "knowledge_attributes",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("entity_id", "TEXT"),
            ("name", "TEXT"),
            ("attribute_type", "TEXT"),
            ("data_type", "TEXT"),
            ("description", "TEXT"),
            ("is_required", "INTEGER"),
            ("default_value", "TEXT"),
            ("constraints", "TEXT"),
            ("validation_rules", "TEXT"),
            ("metadata", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "knowledge_bases",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("embedding_provider", "TEXT"),
            ("enabled", "INTEGER"),
            ("icon_type", "TEXT"),
            ("icon_value", "TEXT"),
            ("sort_order", "INTEGER"),
            ("embedding_dimensions", "INTEGER"),
            ("retrieval_threshold", "REAL"),
            ("retrieval_top_k", "INTEGER"),
            ("chunk_size", "INTEGER"),
            ("chunk_overlap", "INTEGER"),
            ("separator", "TEXT"),
            ("kind", "TEXT"),
            ("vault_path", "TEXT"),
        ],
    ),
    (
        "knowledge_documents",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("title", "TEXT"),
            ("source_path", "TEXT"),
            ("mime_type", "TEXT"),
            ("size_bytes", "BIGINT"),
            ("indexing_status", "TEXT"),
            ("doc_type", "TEXT"),
            ("index_error", "TEXT"),
            ("source_conversation_id", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "knowledge_entities",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("name", "TEXT"),
            ("entity_type", "TEXT"),
            ("description", "TEXT"),
            ("source_path", "TEXT"),
            ("source_language", "TEXT"),
            ("properties", "TEXT"),
            ("lifecycle", "TEXT"),
            ("behaviors", "TEXT"),
            ("metadata", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("aliases", "TEXT"),
            ("mention_count", "INTEGER"),
            ("confidence", "REAL"),
            ("first_seen_at", "TEXT"),
            ("last_seen_at", "TEXT"),
            ("source_type", "TEXT"),
            ("source_id", "TEXT"),
            ("node_type", "TEXT"),
            ("external_id", "TEXT"),
        ],
    ),
    (
        "knowledge_flows",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("name", "TEXT"),
            ("flow_type", "TEXT"),
            ("description", "TEXT"),
            ("source_path", "TEXT"),
            ("steps", "TEXT"),
            ("decision_points", "TEXT"),
            ("error_handling", "TEXT"),
            ("preconditions", "TEXT"),
            ("postconditions", "TEXT"),
            ("metadata", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "knowledge_interfaces",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("name", "TEXT"),
            ("interface_type", "TEXT"),
            ("description", "TEXT"),
            ("source_path", "TEXT"),
            ("input_schema", "TEXT"),
            ("output_schema", "TEXT"),
            ("error_codes", "TEXT"),
            ("communication_pattern", "TEXT"),
            ("version", "TEXT"),
            ("metadata", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "knowledge_relations",
        &[
            ("id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("source_entity_id", "TEXT"),
            ("target_entity_id", "TEXT"),
            ("relation_type", "TEXT"),
            ("description", "TEXT"),
            ("properties", "TEXT"),
            ("metadata", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("weight", "REAL"),
            ("source_type", "TEXT"),
            ("source_id", "TEXT"),
        ],
    ),
    (
        "mcp_servers",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("alias", "TEXT"),
            ("description", "TEXT"),
            ("transport", "TEXT"),
            ("command", "TEXT"),
            ("args_json", "TEXT"),
            ("endpoint", "TEXT"),
            ("env_json", "TEXT"),
            ("enabled", "INTEGER"),
            ("permission_policy", "TEXT"),
            ("source", "TEXT"),
            ("discover_timeout_secs", "INTEGER"),
            ("execute_timeout_secs", "INTEGER"),
            ("headers_json", "TEXT"),
            ("icon_type", "TEXT"),
            ("icon_value", "TEXT"),
        ],
    ),
    (
        "memory_items",
        &[
            ("id", "TEXT"),
            ("namespace_id", "TEXT"),
            ("title", "TEXT"),
            ("content", "TEXT"),
            ("source", "TEXT"),
            ("index_status", "TEXT"),
            ("index_error", "TEXT"),
            ("updated_at", "TEXT"),
            ("tier", "TEXT"),
            ("importance", "REAL"),
            ("access_count", "INTEGER"),
            ("last_accessed", "BIGINT"),
            ("decay_rate", "REAL"),
            ("expires_at", "BIGINT"),
            ("source_conversation_id", "TEXT"),
            ("source_message_id", "TEXT"),
            ("memory_nature", "TEXT"),
            ("tags", "TEXT"),
            ("applicability_tags", "TEXT"),
            ("confirmed", "INTEGER"),
        ],
    ),
    (
        "memory_namespaces",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("scope", "TEXT"),
            ("embedding_provider", "TEXT"),
            ("embedding_dimensions", "INTEGER"),
            ("retrieval_threshold", "REAL"),
            ("retrieval_top_k", "INTEGER"),
            ("icon_type", "TEXT"),
            ("icon_value", "TEXT"),
            ("sort_order", "INTEGER"),
        ],
    ),
    (
        "messages",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("role", "TEXT"),
            ("content", "TEXT"),
            ("provider_id", "TEXT"),
            ("model_id", "TEXT"),
            ("token_count", "BIGINT"),
            ("prompt_tokens", "BIGINT"),
            ("completion_tokens", "BIGINT"),
            ("attachments", "TEXT"),
            ("thinking", "TEXT"),
            ("created_at", "BIGINT"),
            ("branch_id", "TEXT"),
            ("parent_message_id", "TEXT"),
            ("version_index", "INTEGER"),
            ("is_active", "INTEGER"),
            ("tool_calls_json", "TEXT"),
            ("tool_call_id", "TEXT"),
            ("status", "TEXT"),
            ("tokens_per_second", "REAL"),
            ("first_token_latency_ms", "BIGINT"),
            ("cache_creation_tokens", "BIGINT"),
            ("cache_read_tokens", "BIGINT"),
            ("parts", "TEXT"),
            ("quoted_message_id", "TEXT"),
            ("decision", "TEXT"),
        ],
    ),
    (
        "models",
        &[
            ("provider_id", "TEXT"),
            ("model_id", "TEXT"),
            ("name", "TEXT"),
            ("group_name", "TEXT"),
            ("model_type", "TEXT"),
            ("capabilities", "TEXT"),
            ("max_tokens", "BIGINT"),
            ("enabled", "INTEGER"),
            ("param_overrides", "TEXT"),
            ("input_price_per_mtok", "REAL"),
            ("output_price_per_mtok", "REAL"),
        ],
    ),
    (
        "note_backlinks",
        &[
            ("id", "BIGINT"),
            ("vault_id", "TEXT"),
            ("source_note_id", "TEXT"),
            ("target_note_id", "TEXT"),
            ("link_text", "TEXT"),
            ("link_type", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "note_links",
        &[
            ("id", "BIGINT"),
            ("vault_id", "TEXT"),
            ("source_note_id", "TEXT"),
            ("target_note_id", "TEXT"),
            ("link_text", "TEXT"),
            ("link_type", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "notes",
        &[
            ("id", "TEXT"),
            ("vault_id", "TEXT"),
            ("title", "TEXT"),
            ("file_path", "TEXT"),
            ("content", "TEXT"),
            ("content_hash", "TEXT"),
            ("author", "TEXT"),
            ("page_type", "TEXT"),
            ("tags", "TEXT"),
            ("source_refs", "TEXT"),
            ("related_pages", "TEXT"),
            ("quality_score", "REAL"),
            ("last_linted_at", "BIGINT"),
            ("last_compiled_at", "BIGINT"),
            ("compiled_source_hash", "TEXT"),
            ("user_edited", "INTEGER"),
            ("user_edited_at", "BIGINT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("is_deleted", "INTEGER"),
        ],
    ),
    (
        "paper_overviews",
        &[
            ("id", "TEXT"),
            ("document_id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("overview_type", "TEXT"),
            ("abstract_text", "TEXT"),
            ("key_concepts", "TEXT"),
            ("methods", "TEXT"),
            ("contributions", "TEXT"),
            ("limitations", "TEXT"),
            ("tl_dr", "TEXT"),
            ("sections", "TEXT"),
            ("metadata_json", "TEXT"),
            ("generated_by", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "plans",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("user_message_id", "TEXT"),
            ("title", "TEXT"),
            ("steps_json", "TEXT"),
            ("status", "TEXT"),
            ("is_active", "INTEGER"),
            ("created_under_strategy", "TEXT"),
            ("reason", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "program_policies",
        &[
            ("id", "TEXT"),
            ("program_name", "TEXT"),
            ("allowed_provider_ids_json", "TEXT"),
            ("allowed_model_ids_json", "TEXT"),
            ("default_provider_id", "TEXT"),
            ("default_model_id", "TEXT"),
            ("rate_limit_per_minute", "BIGINT"),
        ],
    ),
    (
        "prompt_templates",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("content", "TEXT"),
            ("variables_schema", "TEXT"),
            ("version", "INTEGER"),
            ("is_active", "INTEGER"),
            ("ab_test_enabled", "INTEGER"),
            ("ab_test_variant", "TEXT"),
            ("category", "TEXT"),
            ("tags", "TEXT"),
            ("author", "TEXT"),
            ("source", "TEXT"),
            ("source_type", "TEXT"),
            ("format", "TEXT"),
            ("metadata_json", "TEXT"),
            ("usage_count", "INTEGER"),
            ("is_favorite", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "prompt_template_versions",
        &[
            ("id", "TEXT"),
            ("template_id", "TEXT"),
            ("version", "INTEGER"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("content", "TEXT"),
            ("variables_schema", "TEXT"),
            ("category", "TEXT"),
            ("tags", "TEXT"),
            ("author", "TEXT"),
            ("source", "TEXT"),
            ("changelog", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "provider_keys",
        &[
            ("id", "TEXT"),
            ("provider_id", "TEXT"),
            ("key_encrypted", "TEXT"),
            ("key_prefix", "TEXT"),
            ("enabled", "INTEGER"),
            ("last_validated_at", "BIGINT"),
            ("last_error", "TEXT"),
            ("rotation_index", "INTEGER"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "providers",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("provider_type", "TEXT"),
            ("api_host", "TEXT"),
            ("api_path", "TEXT"),
            ("enabled", "INTEGER"),
            ("proxy_config", "TEXT"),
            ("tool_adaptation", "TEXT"),
            ("tool_adaptation_marker_prefix", "TEXT"),
            ("custom_headers", "TEXT"),
            ("icon", "TEXT"),
            ("builtin_id", "TEXT"),
            ("sort_order", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "reading_list_items",
        &[
            ("id", "TEXT"),
            ("reading_list_id", "TEXT"),
            ("document_id", "TEXT"),
            ("external_url", "TEXT"),
            ("title", "TEXT"),
            ("notes", "TEXT"),
            ("status", "TEXT"),
            ("priority", "INTEGER"),
            ("position", "INTEGER"),
            ("metadata_json", "TEXT"),
            ("added_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "reading_lists",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("owner_user_id", "TEXT"),
            ("status", "TEXT"),
            ("sort_order", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "retrieval_hits",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("message_id", "TEXT"),
            ("knowledge_base_id", "TEXT"),
            ("document_id", "TEXT"),
            ("chunk_ref", "TEXT"),
            ("score", "REAL"),
            ("preview", "TEXT"),
            ("feedback", "TEXT"),
            ("feedback_at", "BIGINT"),
            ("used_in_response", "INTEGER"),
            ("score_after_rerank", "REAL"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "route_history",
        &[
            ("id", "TEXT"),
            ("prompt_hash", "TEXT"),
            ("prompt_preview", "TEXT"),
            ("heuristic_tier", "TEXT"),
            ("selected_tier", "TEXT"),
            ("outcome_success", "INTEGER"),
            ("outcome_quality_score", "REAL"),
            ("outcome_user_override", "INTEGER"),
            ("outcome_user_tier", "TEXT"),
            ("outcome_latency_ms", "BIGINT"),
            ("outcome_tokens_used", "BIGINT"),
            ("outcome_cost_usd", "REAL"),
            ("timestamp", "BIGINT"),
            ("features_json", "TEXT"),
        ],
    ),
    (
        "search_citations",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("message_id", "TEXT"),
            ("title", "TEXT"),
            ("url", "TEXT"),
            ("snippet", "TEXT"),
            ("provider_id", "TEXT"),
            ("rank", "INTEGER"),
        ],
    ),
    (
        "search_providers",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("provider_type", "TEXT"),
            ("endpoint", "TEXT"),
            ("api_key_ref", "TEXT"),
            ("enabled", "INTEGER"),
            ("region", "TEXT"),
            ("language", "TEXT"),
            ("safe_search", "BIGINT"),
            ("result_limit", "INTEGER"),
            ("timeout_ms", "INTEGER"),
        ],
    ),
    ("settings", &[("key", "TEXT"), ("value", "TEXT")]),
    ("skill_states", &[("name", "TEXT"), ("enabled", "INTEGER"), ("updated_at", "BIGINT")]),
    (
        "stored_files",
        &[
            ("id", "TEXT"),
            ("hash", "TEXT"),
            ("original_name", "TEXT"),
            ("mime_type", "TEXT"),
            ("size_bytes", "BIGINT"),
            ("storage_path", "TEXT"),
            ("conversation_id", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "tool_descriptors",
        &[
            ("id", "TEXT"),
            ("server_id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("input_schema_json", "TEXT"),
        ],
    ),
    (
        "tool_executions",
        &[
            ("id", "TEXT"),
            ("conversation_id", "TEXT"),
            ("message_id", "TEXT"),
            ("server_id", "TEXT"),
            ("tool_name", "TEXT"),
            ("status", "TEXT"),
            ("input_preview", "TEXT"),
            ("output_preview", "TEXT"),
            ("error_message", "TEXT"),
            ("duration_ms", "BIGINT"),
            ("created_at", "TEXT"),
            ("approval_status", "TEXT"),
            ("skill_steps_json", "TEXT"),
            ("depends_on", "TEXT"),
        ],
    ),
    (
        "trajectory_trajectories",
        &[
            ("id", "TEXT"),
            ("session_id", "TEXT"),
            ("user_id", "TEXT"),
            ("agent_name", "TEXT"),
            ("topic", "TEXT"),
            ("summary", "TEXT"),
            ("outcome", "TEXT"),
            ("duration_ms", "BIGINT"),
            ("quality_overall", "REAL"),
            ("quality_task_completion", "REAL"),
            ("quality_tool_efficiency", "REAL"),
            ("quality_reasoning_quality", "REAL"),
            ("quality_user_satisfaction", "REAL"),
            ("value_score", "REAL"),
            ("patterns", "TEXT"),
            ("created_at", "TEXT"),
            ("replay_count", "INTEGER"),
            ("last_replay_at", "TEXT"),
            ("is_invalidated", "INTEGER"),
        ],
    ),
    (
        "trajectory_learned_patterns",
        &[
            ("id", "TEXT"),
            ("pattern", "TEXT"),
            ("pattern_type", "TEXT"),
            ("success", "INTEGER"),
            ("failure", "INTEGER"),
            ("last_used", "TEXT"),
            ("created_at", "TEXT"),
            ("metadata", "TEXT"),
        ],
    ),
    (
        "trajectory_messages",
        &[
            ("id", "TEXT"),
            ("session_id", "TEXT"),
            ("role", "TEXT"),
            ("content", "TEXT"),
            ("tool_calls", "TEXT"),
            ("tool_results", "TEXT"),
            ("usage", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "trajectory_patterns",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("pattern_type", "TEXT"),
            ("trajectory_ids", "TEXT"),
            ("frequency", "INTEGER"),
            ("success_rate", "REAL"),
            ("average_quality", "REAL"),
            ("average_value_score", "REAL"),
            ("reward_profile", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "trajectory_preferences",
        &[
            ("id", "TEXT"),
            ("key", "TEXT"),
            ("value", "TEXT"),
            ("confidence", "REAL"),
            ("updated_at", "TEXT"),
        ],
    ),
    (
        "trajectory_rewards",
        &[
            ("id", "TEXT"),
            ("trajectory_id", "TEXT"),
            ("reward_type", "TEXT"),
            ("value", "REAL"),
            ("step_index", "INTEGER"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "trajectory_sessions",
        &[
            ("id", "TEXT"),
            ("title", "TEXT"),
            ("platform", "TEXT"),
            ("user_id", "TEXT"),
            ("model", "TEXT"),
            ("system_prompt", "TEXT"),
            ("created_at", "TEXT"),
            ("updated_at", "TEXT"),
            ("parent_session_id", "TEXT"),
            ("token_input", "BIGINT"),
            ("token_output", "BIGINT"),
        ],
    ),
    (
        "trajectory_skill_executions",
        &[
            ("id", "TEXT"),
            ("skill_id", "TEXT"),
            ("trajectory_id", "TEXT"),
            ("success", "INTEGER"),
            ("execution_time_ms", "BIGINT"),
            ("created_at", "TEXT"),
            ("input_args", "TEXT"),
            ("output_result", "TEXT"),
        ],
    ),
    (
        "trajectory_skills",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("skill_type", "TEXT"),
            ("content", "TEXT"),
            ("category", "TEXT"),
            ("tags", "TEXT"),
            ("scenarios", "TEXT"),
            ("parameters", "TEXT"),
            ("created_at", "TEXT"),
            ("updated_at", "TEXT"),
            ("usage_count", "INTEGER"),
            ("success_rate", "REAL"),
            ("avg_execution_time_ms", "BIGINT"),
            ("consecutive_failures", "INTEGER"),
            ("last_failure_at", "TEXT"),
        ],
    ),
    (
        "trajectory_steps",
        &[
            ("id", "BIGINT"),
            ("trajectory_id", "TEXT"),
            ("step_index", "INTEGER"),
            ("timestamp_ms", "BIGINT"),
            ("role", "TEXT"),
            ("content", "TEXT"),
            ("reasoning", "TEXT"),
            ("tool_calls", "TEXT"),
            ("tool_results", "TEXT"),
        ],
    ),
    (
        "trajectory_workflow_reflections",
        &[
            ("id", "TEXT"),
            ("workflow_id", "TEXT"),
            ("execution_id", "TEXT"),
            ("template_id", "TEXT"),
            ("quality_score", "INTEGER"),
            ("summary", "TEXT"),
            ("error_patterns_json", "TEXT"),
            ("reusable_patterns_json", "TEXT"),
            ("metadata_json", "TEXT"),
            ("timestamp", "TEXT"),
            ("created_at", "TEXT"),
        ],
    ),
    (
        "vec_collections",
        &[
            ("collection_id", "TEXT"),
            ("dimensions", "INTEGER"),
            ("embedding_model", "TEXT"),
            ("index_type", "TEXT"),
            ("hnsw_ef_construction", "INTEGER"),
            ("hnsw_m", "INTEGER"),
            ("hnsw_ef_search", "INTEGER"),
            ("vector_count", "BIGINT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
            ("last_indexed_at", "BIGINT"),
            ("metadata", "TEXT"),
        ],
    ),
    (
        "wiki_operations",
        &[
            ("id", "BIGINT"),
            ("wiki_id", "TEXT"),
            ("operation_type", "TEXT"),
            ("target_type", "TEXT"),
            ("target_id", "TEXT"),
            ("status", "TEXT"),
            ("details_json", "TEXT"),
            ("error_message", "TEXT"),
            ("created_at", "BIGINT"),
            ("completed_at", "BIGINT"),
        ],
    ),
    (
        "wiki_page_versions",
        &[
            ("id", "BIGINT"),
            ("wiki_id", "TEXT"),
            ("note_id", "TEXT"),
            ("title", "TEXT"),
            ("content", "TEXT"),
            ("content_hash", "TEXT"),
            ("author", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "wiki_pages",
        &[
            ("id", "TEXT"),
            ("wiki_id", "TEXT"),
            ("note_id", "TEXT"),
            ("page_type", "TEXT"),
            ("title", "TEXT"),
            ("source_ids", "TEXT"),
            ("quality_score", "REAL"),
            ("last_linted_at", "BIGINT"),
            ("last_compiled_at", "BIGINT"),
            ("compiled_source_hash", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "wiki_sources",
        &[
            ("id", "TEXT"),
            ("wiki_id", "TEXT"),
            ("source_type", "TEXT"),
            ("source_path", "TEXT"),
            ("title", "TEXT"),
            ("mime_type", "TEXT"),
            ("size_bytes", "BIGINT"),
            ("content_hash", "TEXT"),
            ("metadata_json", "TEXT"),
            ("schedule_cron", "TEXT"),
            ("last_fetched_at", "INTEGER"),
            ("status", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "wiki_sync_queue",
        &[
            ("id", "BIGINT"),
            ("wiki_id", "TEXT"),
            ("event_type", "TEXT"),
            ("target_type", "TEXT"),
            ("target_id", "TEXT"),
            ("payload", "TEXT"),
            ("status", "TEXT"),
            ("retry_count", "INTEGER"),
            ("error_message", "TEXT"),
            ("created_at", "BIGINT"),
            ("processed_at", "BIGINT"),
        ],
    ),
    (
        "wiki_templates",
        &[
            ("id", "TEXT"),
            ("wiki_id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("content", "TEXT"),
            ("page_type", "TEXT"),
            ("is_builtin", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "wikis",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("root_path", "TEXT"),
            ("schema_version", "TEXT"),
            ("note_count", "INTEGER"),
            ("source_count", "INTEGER"),
            ("embedding_provider", "TEXT"),
            ("embedding_dimensions", "INTEGER"),
            ("retrieval_threshold", "REAL"),
            ("retrieval_top_k", "INTEGER"),
            ("knowledge_base_id", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "workflow_approvals",
        &[
            ("id", "TEXT"),
            ("execution_id", "TEXT"),
            ("node_id", "TEXT"),
            ("status", "TEXT"),
            ("title", "TEXT"),
            ("message", "TEXT"),
            ("approver", "TEXT"),
            ("channels", "TEXT"),
            ("payload", "TEXT"),
            ("decision", "TEXT"),
            ("approver_actual", "TEXT"),
            ("comment", "TEXT"),
            ("timeout_action", "TEXT"),
            ("timeout_secs", "BIGINT"),
            ("expires_at", "BIGINT"),
            ("created_at", "BIGINT"),
            ("resolved_at", "BIGINT"),
        ],
    ),
    (
        "workflow_execution_stats",
        &[
            ("id", "TEXT"),
            ("mission_hash", "TEXT"),
            ("template_id", "TEXT"),
            ("execution_id", "TEXT"),
            ("status", "TEXT"),
            ("total_time_ms", "BIGINT"),
            ("input_tokens", "BIGINT"),
            ("output_tokens", "BIGINT"),
            ("error_message", "TEXT"),
            ("user_rating", "REAL"),
            ("created_at", "BIGINT"),
        ],
    ),
    (
        "workflow_executions",
        &[
            ("id", "TEXT"),
            ("workflow_id", "TEXT"),
            ("status", "TEXT"),
            ("input_params", "TEXT"),
            ("output_result", "TEXT"),
            ("node_executions", "TEXT"),
            ("execution_state_json", "TEXT"),
            ("paused_at", "BIGINT"),
            ("total_time_ms", "BIGINT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "workflow_marketplace",
        &[
            ("id", "TEXT"),
            ("template_id", "TEXT"),
            ("author_id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("category", "TEXT"),
            ("icon", "TEXT"),
            ("tags", "TEXT"),
            ("downloads", "BIGINT"),
            ("rating_average", "REAL"),
            ("rating_count", "INTEGER"),
            ("is_featured", "INTEGER"),
            ("is_verified", "INTEGER"),
            ("is_public", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "workflow_marketplace_reviews",
        &[
            ("id", "TEXT"),
            ("marketplace_id", "TEXT"),
            ("user_id", "TEXT"),
            ("rating", "INTEGER"),
            ("comment", "TEXT"),
            ("is_hidden", "INTEGER"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "workflow_snapshots",
        &[
            ("id", "TEXT"),
            ("workflow_id", "TEXT"),
            ("snapshot_json", "TEXT"),
            ("created_at", "BIGINT"),
            ("step_id", "TEXT"),
        ],
    ),
    (
        "workflow_templates",
        &[
            ("id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("icon", "TEXT"),
            ("tags", "TEXT"),
            ("version", "INTEGER"),
            ("is_preset", "INTEGER"),
            ("is_editable", "INTEGER"),
            ("is_public", "INTEGER"),
            ("trigger_config", "TEXT"),
            ("nodes", "TEXT"),
            ("edges", "TEXT"),
            ("input_schema", "TEXT"),
            ("output_schema", "TEXT"),
            ("variables", "TEXT"),
            ("error_config", "TEXT"),
            ("composite_source", "TEXT"),
            ("tool_defs", "TEXT"),
            ("mission_hash", "TEXT"),
            ("cluster_id", "TEXT"),
            ("route_path", "TEXT"),
            ("hooks_config", "TEXT"),
            ("created_at", "BIGINT"),
            ("updated_at", "BIGINT"),
        ],
    ),
    (
        "workflow_template_versions",
        &[
            ("id", "TEXT"),
            ("template_id", "TEXT"),
            ("name", "TEXT"),
            ("description", "TEXT"),
            ("icon", "TEXT"),
            ("tags", "TEXT"),
            ("version", "INTEGER"),
            ("is_preset", "INTEGER"),
            ("is_editable", "INTEGER"),
            ("is_public", "INTEGER"),
            ("trigger_config", "TEXT"),
            ("nodes", "TEXT"),
            ("edges", "TEXT"),
            ("input_schema", "TEXT"),
            ("output_schema", "TEXT"),
            ("variables", "TEXT"),
            ("error_config", "TEXT"),
            ("created_at", "BIGINT"),
        ],
    ),
];

#[tokio::test]
async fn verify_all_entity_columns_exist_in_db() {
    let db = Database::connect("sqlite::memory:").await.expect("测试应成功");

    // 跑全部迁移
    axagent_dao::migrations::run_migrations(&db)
        .await
        .expect("all migrations should apply cleanly");

    let mut errors: Vec<String> = Vec::new();

    for &(table_name, expected_cols) in SCHEMA {
        // 读 DB 实际列
        let rows = db
            .query_all_raw(Statement::from_sql_and_values(
                DbBackend::Sqlite,
                "SELECT name FROM pragma_table_info(?) ORDER BY cid",
                [table_name.into()],
            ))
            .await
            .unwrap_or_else(|e| {
                errors.push(format!("表 {table_name}: 读取 pragma_table_info 失败: {e}"));
                vec![]
            });

        let actual_cols: Vec<String> =
            rows.iter().filter_map(|r| r.try_get_by::<String, _>("name").ok()).collect();

        for &(col_name, col_type) in expected_cols {
            if actual_cols.iter().any(|c| c == col_name) {
                continue;
            }
            errors.push(format!("表 {table_name}: 缺失列 {col_name} ({col_type})"));
        }

        // 可选：检查多余列（警告级别）
        for actual in &actual_cols {
            if !expected_cols.iter().any(|(name, _)| name == actual) {
                errors.push(format!(
                    "表 {table_name}: DB 有多余列 {actual}（不在实体定义中但可能正常）"
                ));
            }
        }
    }

    let missing = errors.iter().filter(|e| e.contains("缺失列")).count();
    let extra = errors.iter().filter(|e| e.contains("多余列")).count();

    assert!(
        errors.is_empty(),
        "Schema 合规性检查失败！\n\
         存在 {missing} 列缺失 + {extra} 列多余：\n{}\n\
         说明：缺失列=实体定义但 DB 中没有（bug）；多余列=DB 有但实体没有（通常无害）",
        errors.join("\n")
    );

    // 成功时打印汇总
    tracing::info!("[schema_compliance] 检查通过，0 缺失，0 多余（{} 张表）", SCHEMA.len());
}
