/**
 * add_serenity_panel.js
 * 向所有 11 个 i18n 语言文件的 "serenityPanel" 键插入翻译。
 * 用法: node add_serenity_panel.js
 */

const fs = require("fs");
const path = require("path");

const LOCALES_DIR = path.join(__dirname, "..", "src", "i18n", "locales");

// 基准翻译（zh-CN）
const serenityPanelZh = {
  desc: "Serenity 瓶颈分析法：从市场数据中发现产业链瓶颈环节，自动筛选潜在标的",
  run: "运行 Serenity 筛选",
  running: "筛选中...",
  stage_loading: "加载工作流模板...",
  stage_scanning: "阶段 0/4: 扫描市场趋势",
  stage_decomposing: "阶段 1/4: 拆解产业链",
  stage_identifying: "阶段 2/4: 鉴定瓶颈环节",
  stage_mapping: "阶段 3/4: 映射候选公司",
  stage_saving: "阶段 4/4: 保存结果",
  stage_done: "筛选完成",
  stage_error: "筛选失败",
  analyzing: "正在分析产业链数据，LLM 推理需要 1-3 分钟...",
  trendTitle: "发现的产业趋势",
  bottleneckLink: "瓶颈环节: ",
  candidateTitle: "候选标的",
  directBenefit: "直接受益",
  indirectBenefit: "间接受益",
  themeRelated: "主题相关",
  bottleneckProduct: "瓶颈产品: ",
  riskPrefix: "风险: ",
  confidencePrefix: "置信度 ",
  scoreSuffix: "分",
  emptyHint: "点击上方按钮运行 Serenity 瓶颈筛选",
  errorUnknown: "未知错误",
  callFailed: "调用失败",
};

// 各语言翻译映射（key = 文件名去掉 .json）
const translations = {
  "zh-CN": serenityPanelZh,
  "en-US": {
    desc:
      "Serenity bottleneck method: automatically screen potential stocks by discovering bottleneck links in the industry chain from market data",
    run: "Run Serenity Screen",
    running: "Screening...",
    stage_loading: "Loading workflow template...",
    stage_scanning: "Stage 0/4: Scanning market trends",
    stage_decomposing: "Stage 1/4: Decomposing industry chain",
    stage_identifying: "Stage 2/4: Identifying bottleneck links",
    stage_mapping: "Stage 3/4: Mapping candidate companies",
    stage_saving: "Stage 4/4: Saving results",
    stage_done: "Screening completed",
    stage_error: "Screening failed",
    analyzing: "Analyzing industry chain data, LLM reasoning requires 1-3 minutes...",
    trendTitle: "Discovered industry trends",
    bottleneckLink: "Bottleneck link: ",
    candidateTitle: "Candidate targets",
    directBenefit: "Direct beneficiary",
    indirectBenefit: "Indirect beneficiary",
    themeRelated: "Theme related",
    bottleneckProduct: "Bottleneck product: ",
    riskPrefix: "Risk: ",
    confidencePrefix: "Confidence ",
    scoreSuffix: " points",
    emptyHint: "Click the button above to run Serenity bottleneck screening",
    errorUnknown: "Unknown error",
    callFailed: "Call failed",
  },
  "zh-TW": {
    desc: "Serenity 瓶頸分析法：從市場數據中發現產業鏈瓶頸環節，自動篩選潛在標的",
    run: "運行 Serenity 篩選",
    running: "篩選中...",
    stage_loading: "載入工作流範本...",
    stage_scanning: "階段 0/4: 掃描市場趨勢",
    stage_decomposing: "階段 1/4: 拆解產業鏈",
    stage_identifying: "階段 2/4: 鑑定瓶頸環節",
    stage_mapping: "階段 3/4: 映射候選公司",
    stage_saving: "階段 4/4: 儲存結果",
    stage_done: "篩選完成",
    stage_error: "篩選失敗",
    analyzing: "正在分析產業鏈數據，LLM 推理需要 1-3 分鐘...",
    trendTitle: "發現的產業趨勢",
    bottleneckLink: "瓶頸環節: ",
    candidateTitle: "候選標的",
    directBenefit: "直接受益",
    indirectBenefit: "間接受益",
    themeRelated: "主題相關",
    bottleneckProduct: "瓶頸產品: ",
    riskPrefix: "風險: ",
    confidencePrefix: "置信度 ",
    scoreSuffix: "分",
    emptyHint: "點擊上方按鈕運行 Serenity 瓶頸篩選",
    errorUnknown: "未知錯誤",
    callFailed: "呼叫失敗",
  },
  "de": {
    desc:
      "Serenity Flaschenhalsmethode: Automatisches Screeining potenzieller Aktien durch Entdeckung von Flaschenhalsverbindungen in der Industriekette aus Marktdaten",
    run: "Serenity Screeining ausführen",
    running: "Screeining...",
    stage_loading: "Workflow-Vorlage wird geladen...",
    stage_scanning: "Stufe 0/4: Markttrends scannen",
    stage_decomposing: "Stufe 1/4: Industriekette zerlegen",
    stage_identifying: "Stufe 2/4: Flaschenhalsverbindungen identifizieren",
    stage_mapping: "Stufe 3/4: Kandidatenunternehmen zuordnen",
    stage_saving: "Stufe 4/4: Ergebnisse speichern",
    stage_done: "Screeining abgeschlossen",
    stage_error: "Screeining fehlgeschlagen",
    analyizing: "Analysiere Industriekettendaten, LLM-Inferenz benötigt 1-3 Minuten...",
    trendTitle: "Entdeckte Industrietrends",
    bottleneckLink: "Flaschenhals: ",
    candidateTitle: "Kandidatentitel",
    directBenefit: "Direkter Begünstigter",
    indirectBenefit: "Indirekter Begünstigter",
    themeRelated: "Themenbezogen",
    bottleneckProduct: "Flaschenhalsprodukt: ",
    riskPrefix: "Risiko: ",
    confidencePrefix: "Konfidenz ",
    scoreSuffix: " Punkte",
    emptyHint: "Klicken Sie auf die obige Schaltfläche, um die Serenity-Flaschenhals-Screeining auszuführen",
    errorUnknown: "Unbekannter Fehler",
    callFailed: "Aufruf fehlgeschlagen",
  },
  "fr": {
    desc:
      "Méthode des goulots Serenity : cribler automatiquement les actions potentielles en découvrant les liaisons des goulots dans la chaîne industrielle à partir des données du marché",
    run: "Exécuter le criblage Serenity",
    running: "Criblage...",
    stage_loading: "Chargement du modèle de workflow...",
    stage_scanning: "Étape 0/4 : Analyse des tendances du marché",
    stage_decomposing: "Étape 1/4 : Décomposition de la chaîne industrielle",
    stage_identifying: "Étape 2/4 : Identification des liaisons des goulots",
    stage_mapping: "Étape 3/4 : Mappage des entreprises candidates",
    stage_saving: "Étape 4/4 : Enregistrement des résultats",
    stage_done: "Criblage terminé",
    stage_error: "Échec du criblage",
    analyizing: "Analyse des données de la chaîne industrielle, le raisonnement LLM nécessite 1-3 minutes...",
    trendTitle: "Tendances industrielles découvertes",
    bottleneckLink: "Liaison du goulot : ",
    candidateTitle: "Cibles candidates",
    directBenefit: "Bénéficiaire direct",
    indirectBenefit: "Bénéficiaire indirect",
    themeRelated: "Thème associé",
    bottleneckProduct: "Produit du goulot : ",
    riskPrefix: "Risque : ",
    confidencePrefix: "Confiance ",
    scoreSuffix: " points",
    emptyHint: "Cliquez sur le bouton ci-dessus pour exécuter le criblage des goulots Serenity",
    errorUnknown: "Erreur inconnue",
    callFailed: "Échec de l'appel",
  },
  "ru": {
    desc:
      "Метод узких мест Serenity: автоматический отбор потенциальных акций путем обнаружения узких мест в производственной цепочке из данных рынка",
    run: "Запустить отбор Serenity",
    running: "Отбор...",
    stage_loading: "Загрузка шаблона рабочего процесса...",
    stage_scanning: "Этап 0/4: Сканирование рыночных трендов",
    stage_decomposing: "Этап 1/4: Декомпозиция производственной цепочки",
    stage_identifying: "Этап 2/4: Идентификация узких мест",
    stage_mapping: "Этап 3/4: Сопоставление компаний-кандидатов",
    stage_saving: "Этап 4/4: Сохранение результатов",
    stage_done: "Отбор завершен",
    stage_error: "Ошибка отбора",
    analyizing: "Анализ данных производственной цепочки, вывод LLM требует 1-3 минуты...",
    trendTitle: "Обнаруженные тренды отрасли",
    bottleneckLink: "Узкое место: ",
    candidateTitle: "Кандидаты",
    directBenefit: "Прямой выгодоприобретатель",
    indirectBenefit: "Косвенный выгодоприобретатель",
    themeRelated: "Тема связана",
    bottleneckProduct: "Продукт узкого места: ",
    riskPrefix: "Риск: ",
    confidencePrefix: "Уверенность ",
    scoreSuffix: " баллов",
    emptyHint: "Нажмите кнопку выше, чтобы запустить отбор узких мест Serenity",
    errorUnknown: "Неизвестная ошибка",
    callFailed: "Вызов не удался",
  },
  "hi": {
    desc:
      "Serenity बॉतलनेक विधि: बाजार के डेटा से उद्योग श्रृंखला में बॉतलनेक लिंक की खोज करके स्वचालित रूप से संभावित स्टॉकों को स्क्रीन करें",
    run: "Serenity स्क्रीनिंग चलाएं",
    running: "स्क्रीनिंग...",
    stage_loading: "वर्कफ्लो टेम्पलेट लोड हो रहा है...",
    stage_scanning: "चरण 0/4: बाजार के रुझानों को स्केन करना",
    stage_decomposing: "चरण 1/4: उद्योग श्रृंखला को विघटित करना",
    stage_identifying: "चरण 2/4: बॉतलनेक लिंक की पहचान करना",
    stage_mapping: "चरण 3/4: उम्मीदवार कंपनियों का मैपिंग",
    stage_saving: "चरण 4/4: परिणामों को सहेजना",
    stage_done: "स्क्रीनिंग पूर्ण",
    stage_error: "स्क्रीनिंग विफल",
    analyizing: "उद्योग श्रृंखला डेटा का विश्लेषण, LLM तर्क को 1-3 मिनट चाहिए...",
    trendTitle: "खोजी गई उद्योग tren्ड",
    bottleneckLink: "बॉतलनेक लिंक: ",
    candidateTitle: "उम्मीदवार लक्ष्य",
    directBenefit: "प्रत्यक्ष लाभार्थी",
    indirectBenefit: "अप्रत्यक्ष लाभार्थी",
    themeRelated: "विषय संबंधित",
    bottleneckProduct: "बॉतलनेक उत्पाद: ",
    riskPrefix: "जोखिम: ",
    confidencePrefix: "विश्वास ",
    scoreSuffix: " अंक",
    emptyHint: "Serenity बॉतलनेक स्क्रीनिंग चलाने के लिए ऊपर बटन पर क्लिक करें",
    errorUnknown: "अज्ञात त्रुटि",
    callFailed: "कॉल विफल",
  },
  "ja": {
    desc:
      "Serenity ボトルネック法：市場データから産業チェーン内のボトルネックリンクを発見し、潜在的な銘柄を自動スクリーニングします",
    run: "Serenity スクリーニングを実行",
    running: "スクリーニング中...",
    stage_loading: "ワークフローテンプレートを読み込み中...",
    stage_scanning: "ステージ 0/4: 市場トレンドのスキャン",
    stage_decomposing: "ステージ 1/4: 産業チェーンの分解",
    stage_identifying: "ステージ 2/4: ボトルネックリンクの特定",
    stage_mapping: "ステージ 3/4: 候補企業のマッピング",
    stage_saving: "ステージ 4/4: 結果の保存",
    stage_done: "スクリーニング完了",
    stage_error: "スクリーニング失敗",
    analyizing: "産業チェーンデータを分析中、LLM 推論には 1-3 分鐘かかります...",
    trendTitle: "発見された産業トレンド",
    bottleneckLink: "ボトルネック: ",
    candidateTitle: "候補銘柄",
    directBenefit: "直接受益",
    indirectBenefit: "間接受益",
    themeRelated: "テーマ関連",
    bottleneckProduct: "ボトルネック製品: ",
    riskPrefix: "リスク: ",
    confidencePrefix: "信頼度 ",
    scoreSuffix: " 点",
    emptyHint: "上のボタンをクリックして Serenity ボトルネック・スクリーニングを実行",
    errorUnknown: "未知のエラー",
    callFailed: "呼び出し失敗",
  },
  "ko": {
    desc: "Serenity 병목 방법: 시장 데이터에서 산업 체인 내 병목 링크를 발견하여 잠재적 주식을 자동으로 스크리닝합니다",
    run: "Serenity 스크리닝 실행",
    running: "스크리닝 중...",
    stage_loading: "워크플로우 템플릿 로드 중...",
    stage_scanning: "단계 0/4: 시장 트렌드 스캔",
    stage_decomposing: "단계 1/4: 산업 체인 분해",
    stage_identifying: "단계 2/4: 병목 링크 식별",
    stage_mapping: "단계 3/4: 후보 기업 매핑",
    stage_saving: "단계 4/4: 결과 저장",
    stage_done: "스크리닝 완료",
    stage_error: "스크리닝 실패",
    analyizing: "산업 체인 데이터 분석 중, LLM 추론에 1-3 분 소요...",
    trendTitle: "발견된 산업 트렌드",
    bottleneckLink: "병목: ",
    candidateTitle: "후보 대상",
    directBenefit: "직접 수혜",
    indirectBenefit: "간접 수혜",
    themeRelated: "테마 관련",
    bottleneckProduct: "병목 제품: ",
    riskPrefix: "위험: ",
    confidencePrefix: "신뢰도 ",
    scoreSuffix: " 점",
    emptyHint: "위 버튼을 클릭하여 Serenity 병목 스크리닝 실행",
    errorUnknown: "알 수 없는 오류",
    callFailed: "호출 실패",
  },
  "es": {
    desc:
      "Método de cuellos de botella Serenity: cribar automáticamente acciones potenciales descubriendo enlaces de cuellos de botella en la cadena industrial a partir de datos del mercado",
    run: "Ejecutar cribado Serenity",
    running: "Cribando...",
    stage_loading: "Cargando plantilla de flujo de trabajo...",
    stage_scanning: "Etapa 0/4: Escaneando tendencias del mercado",
    stage_decomposing: "Etapa 1/4: Descomponiendo cadena industrial",
    stage_identifying: "Etapa 2/4: Identificando enlaces de cuellos de botella",
    stage_mapping: "Etapa 3/4: Mapeando empresas candidatas",
    stage_saving: "Etapa 4/4: Guardando resultados",
    stage_done: "Cribado completado",
    stage_error: "Fallo en el cribado",
    analyizing: "Analizando datos de la cadena industrial, el razonamiento LLM requiere 1-3 minutos...",
    trendTitle: "Tendencias industriales descubiertas",
    bottleneckLink: "Enlace de cuello de botella: ",
    candidateTitle: "Objetivos candidatos",
    directBenefit: "Beneficiario directo",
    indirectBenefit: "Beneficiario indirecto",
    themeRelated: "Tema relacionado",
    bottleneckProduct: "Producto de cuello de botella: ",
    riskPrefix: "Riesgo: ",
    confidencePrefix: "Confianza ",
    scoreSuffix: " puntos",
    emptyHint: "Haga clic en el botón de arriba para ejecutar el cribado de cuellos de botella Serenity",
    errorUnknown: "Error desconocido",
    callFailed: "Llamada fallida",
  },
  "ar": {
    desc:
      "طريقة اختناقات Serenity: فحص تلقائي للأسهم المحتملة من خلال اكتشاف روابط اختناق في سلسلة الصناعة من بيانات السوق",
    run: "تشغيل فحص Serenity",
    running: "جاري الفحص...",
    stage_loading: "جاري تحميل قالب سير العمل...",
    stage_scanning: "المرحلة 0/4: مسح اتجاهات السوق",
    stage_decomposing: "المرحلة 1/4: تفكيك سلسلة الصناعة",
    stage_identifying: "المرحلة 2/4: تحديد روابط الاختناق",
    stage_mapping: "المرحلة 3/4: ربط الشركات المرشحة",
    stage_saving: "المرحلة 4/4: حفظ النتائج",
    stage_done: "اكتمل الفحص",
    stage_error: "فشل الفحص",
    analyizing: "جاري تحليل بيانات سلسلة الصناعة, يتطلب استنتاج LLM 1-3 دقائق...",
    trendTitle: "اتجاهات الصناعة المكتشفة",
    bottleneckLink: "رابط الاختناق: ",
    candidateTitle: "الأهداف المرشحة",
    directBenefit: "مستفيد مباشر",
    indirectBenefit: "مستفيد غیر مباشر",
    themeRelated: "موضوع ذو صلة",
    bottleneckProduct: "منتج الاختناق: ",
    riskPrefix: "المخاطر: ",
    confidencePrefix: "الثقة ",
    scoreSuffix: " نقطة",
    emptyHint: "انقر على الزر أعلاه لتشغيل فحص اختناقات Serenity",
    errorUnknown: "خطأ غير معروف",
    callFailed: "فشل الاتصال",
  },
};

function addSerenityPanel(filePath, langKey) {
  const content = fs.readFileSync(filePath, "utf8");
  const json = JSON.parse(content);
  if (!json.serenityPanel) {
    json.serenityPanel = translations[langKey];
    fs.writeFileSync(filePath, JSON.stringify(json, null, 2), "utf8");
    console.log(`✅ Wrote serenityPanel to ${path.basename(filePath)}`);
  } else {
    console.log(`⚠️  serenityPanel already exists in ${path.basename(filePath)}, skipping.`);
  }
}

const files = fs.readdirSync(LOCALES_DIR).filter(f => f.endsWith(".json"));
let done = 0;
for (const file of files) {
  const langKey = file.replace(".json", "");
  if (translations[langKey]) {
    addSerenityPanel(path.join(LOCALES_DIR, file), langKey);
    done++;
  } else {
    console.log(`⚠️  No translation found for ${langKey}, skipping.`);
  }
}
console.log(`\nDone: ${done} files updated.`);
