const fs = require("fs");

const zhCNUpdates = {
  "chatMarkdown.toggleRaw": "切换原始",
  "chatMarkdown.viewThinking": "查看思考",
  "chatMarkdown.inputParams": "输入参数",
  "chatMarkdown.outputResult": "输出结果",
  "chat.context.tokenMax": "Token上限",
  "chat.diff.accept": "接受",
  "chat.diff.reject": "拒绝",
  "chat.diff.accepted": "已接受",
  "chat.diff.rejected": "已拒绝",
  "chat.diff.fileChanges": "文件变更",
  "chat.diff.collapseAll": "全部折叠",
  "chat.diff.expandAll": "全部展开",
  "chat.diff.acceptAll": "全部接受",
  "chat.selfEvolution": "自我进化",
  "chat.tracer": "追踪器",
  "chat.tracerTitle": "追踪器标题",
  "chat.traces": "追踪",
  "chat.spans": "跨度",
  "chat.errors": "错误",
  "chat.active": "活跃",
  "chat.noTraces": "无追踪",
  "plan.status.reviewing": "审核中",
  "plan.status.executing": "执行中",
  "plan.justNow": "刚刚",
  "plan.minutesAgo": "{{count}}分钟前",
  "plan.hoursAgo": "{{count}}小时前",
  "error.page": "错误",
  "advanced.bashSecurity": "Bash安全",
  "advanced.dangerousCmdDetect": "危险命令检测",
  "advanced.networkCmdDetect": "网络命令检测",
  "advanced.cmdTimeout": "命令超时",
  "advanced.permissionStrategy": "权限策略",
  "advanced.defaultPermission": "默认权限",
  "advanced.perm.default": "默认",
  "advanced.perm.acceptEdits": "接受编辑",
  "advanced.perm.fullAccess": "完全访问",
  "advanced.fileWriteConfirm": "文件写入确认",
  "advanced.networkConfirm": "网络确认",
  "advanced.shellConfirm": "Shell确认",
  "common.operationFailed": "操作失败",
  "common.hide": "隐藏",
  "common.searchPlaceholder": "搜索...",
  "hookLog.column.time": "时间",
  "hookLog.column.event": "事件",
  "hookLog.column.tool": "工具",
  "hookLog.column.command": "命令",
  "hookLog.column.status": "状态",
  "hookLog.success": "成功",
  "hookLog.failed": "失败",
  "hookLog.column.outputSummary": "输出摘要",
  "hookLog.filterLabel": "筛选",
  "hookLog.allEvents": "所有事件",
  "hookLog.recordCount": "{{count}}条记录",
  "hookLog.clear": "清除",
  "hookLog.emptyStatus": "无状态",
  "hookLog.emptyFiltered": "无匹配记录",
  "mcp.enabled": "已启用",
  "mcp.disabled": "已禁用",
  "settings.memory.promoteSuccess": "记忆已提升",
  "settings.memory.demoteSuccess": "记忆已降级",
  "settings.memory.feedbackSuccess": "反馈已记录",
  "settings.memory.ageJustNow": "刚刚",
  "settings.memory.ageMinutes": "{{count}}分钟",
  "settings.memory.ageHours": "{{count}}小时",
  "settings.memory.ageDays": "{{count}}天",
  "settings.memory.noWorkingMemory": "无工作记忆",
  "settings.memory.clusterLabel": "聚类",
  "settings.memory.avgImportance": "平均重要性",
  "settings.memory.noKnowledgeGraph": "无知识图谱",
  "settings.memory.target": "目标",
  "settings.expertPromptNote": "专家提示词备注",
  "settings.modelGroupPlaceholder": "选择模型组",
  "settings.localTools.empty": "无本地工具",
  "settings.workflow.myWorkflows": "我的工作流",
  "settings.workflow.marketplace": "市场",
  "settings.scheduler.executed": "已执行",
  "settings.scheduler.quickCreated": "快速创建",
  "settings.scheduler.refreshed": "已刷新",
  "scheduler.refresh": "刷新",
  "scheduler.dailyReport": "日报",
  "scheduler.backup": "备份",
  "scheduler.cleanup": "清理",
  "scheduler.executeNow": "立即执行",
  "scheduler.executionHistory": "执行历史",
  "scheduler.historyTitle": "历史",
  "scheduler.noRecords": "无记录",
  "scheduler.success": "成功",
  "scheduler.failed": "失败",
  "profile.description": "描述",
  "profile.codingStyleDesc": "编码风格",
  "profile.namingConventionDesc": "命名规范",
  "profile.indentationStyleDesc": "缩进风格",
  "profile.commentStyleDesc": "注释风格",
  "profile.communicationDesc": "沟通方式",
  "profile.detailLevelDesc": "详细程度",
  "profile.toneDesc": "语气",
  "profile.languageDesc": "语言",
  "profile.confidenceDesc": "置信度",
  "wiki.backlinks": "反向链接",
  "wiki.noBacklinks": "无反向链接",
  "wiki.tags": "标签",
  "wiki.versionRestored": "版本已恢复",
  "wiki.versionHistory": "版本历史",
  "wiki.noVersions": "无版本",
  "wiki.compareDiff": "对比差异",
  "wiki.confirmRestore": "确认恢复？",
  "wiki.restore": "恢复",
  "wiki.diffLabel": "差异",
  "wiki.selectNote": "选择笔记",
  "wiki.close": "关闭",
  "wiki.edit": "编辑",
  "wiki.unsaved": "未保存",
  "wiki.outlinks": "出站链接",
  "wiki.noOutlinks": "无出站链接",
  "wiki.localGraph": "本地图谱",
  "wiki.noTags": "无标签",
  "wiki.viewBacklinks": "查看反向链接",
  "wiki.focusLocal": "聚焦本地",
  "wiki.createLinkedNote": "创建关联笔记",
  "wiki.delete": "删除",
  "wiki.cancel": "取消",
  "markdown": "Markdown",
  "success": "成功",
  "error": "错误",
};

const zh = JSON.parse(fs.readFileSync("src/i18n/locales/zh-CN.json", "utf8"));

function addKey(obj, key, value) {
  const parts = key.split(".");
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const p = parts[i];
    if (!current[p]) { current[p] = {}; }
    current = current[p];
  }
  current[parts[parts.length - 1]] = value;
}

for (const [key, value] of Object.entries(zhCNUpdates)) {
  addKey(zh, key, value);
}

fs.writeFileSync("src/i18n/locales/zh-CN.json", JSON.stringify(zh, null, 2) + "\n");
console.log("Updated zh-CN.json with Chinese translations");
