[package]
name = "axagent-storage"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait = "0.1"
axagent-entities = { path = "../entities" }
axagent-harness = { path = "../harness" }
axagent-kit = { path = "../kit" }
chrono = { workspace = true }
dirs = "6"
hex = "0.4"
md5 = "0.8"
parking_lot = "0.12"
reqwest = { workspace = true }
roxmltree = "0.21"
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = "0.11"
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
zip = "8"

[dev-dependencies]
axagent-dao = { path = "../dao" }
serial_test = "3"
tempfile = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(mobile)"] }
