[package]
name = "axagent-rt-messaging"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
tokio = { workspace = true, features = ["io-std", "io-util", "macros", "process", "rt", "rt-multi-thread", "sync", "time"] }
async-trait = "0.1"
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true, features = ["multipart", "cookies"] }
uuid = { workspace = true }
flate2 = "1"
zstd = { version = "0.13", features = ["experimental"] }
futures = "0.3"
sha2 = { workspace = true }
axum = "0.8"
axagent-core = { path = "../core" }
axagent-harness = { path = "../harness" }
axagent-providers = { path = "../providers" }
sea-orm = { workspace = true }
tokio-tungstenite = { version = "0.29", features = ["native-tls"] }
sha1 = "0.10"
anyhow = { workspace = true }
roxmltree = "0.20"
url = "2"
regex = "1"

[lints]
# workspace = true
