// SPDX-License-Identifier: AGPL-3.0-only

//! 构建脚本：自动扫描 axagent-entities 的 lib.rs，提取全部 `pub mod` 声明，
//! 生成实体模块注册表到 OUT_DIR/entity_registry.rs，供 schema_diff 的
//! 全库列 diff 使用——**新增实体无需手工登记**。
//!
//! 与主 crate build.rs 生成 register_commands.rs 同构：清单的唯一权威
//! 是 entities/src/lib.rs，build 期从磁盘读取，编译进二进制。

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR 应存在"));
    let entities_lib = manifest_dir.join("../entities/src/lib.rs");
    println!("cargo:rerun-if-changed={}", entities_lib.display());
    // 实体注册表内容随 lib.rs 变化，rerun 后需重编本 crate
    println!("cargo:rerun-if-changed=build.rs");

    let source = fs::read_to_string(&entities_lib)
        .unwrap_or_else(|e| panic!("读取实体清单 {} 失败: {e}", entities_lib.display()));

    // 提取 `pub mod xxx;` —— 顺序无关，仅收集模块名（即实体模块）
    let mut modules: Vec<String> = Vec::new();
    for line in source.lines() {
        let line = line.trim();
        let Some(rest) = line.strip_prefix("pub mod ") else { continue };
        let Some(name) = rest.strip_suffix(';') else { continue };
        let name = name.trim();
        if !name.is_empty()
            && name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        {
            modules.push(name.to_string());
        }
    }
    if modules.is_empty() {
        panic!("从 {} 未提取到任何 pub mod，实体注册表为空", entities_lib.display());
    }

    let generated = format!(
        "// @generated by crates/dao/build.rs —— 请勿手改，实体清单权威在 crates/entities/src/lib.rs\n\
         macro_rules! entity_modules {{\n    ($cb:ident) => {{\n        $cb!({});\n    }};\n}}\n",
        modules.join(", "),
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR 应存在"));
    fs::write(out_dir.join("entity_registry.rs"), generated).expect("写 entity_registry.rs 应成功");
}
