// i18n-exempt: 配置映射表/业务数据字符串，非用户可见 UI 文案

/**
 * 股票分析 AgentProfile 的五张平行映射表。
 *
 * ── 为什么必须齐 ──
 * `AgentProfileList.loadAll()` 在拿不到模板节点时会走「离线回退」分支，用
 * `Object.keys(PROFILE_NAMES)` 驱动渲染 —— **少一个 key 就凭空少一行**；
 * `PROFILE_ROLE_IDS` / `PROFILE_ROLES` 缺 key 时会静默兜底成空串 / "-"。
 * 2026-09-14 之前这里只有 16 个 key（缺 22 个已在后端注册的专家 + 新补的
 * `explainer`），离线回退直接漏掉一半专家。
 *
 * ── 唯一权威 ──
 * key 集合必须等于后端 `src-tauri/src/commands/stock_analysis_setup/mod.rs`
 * 的 `EXPERT_ROLE_MAP` 全集（39 个专家），`PROFILE_ROLE_IDS` 的值必须与
 * `EXPERT_ROLE_MAP` 的 role 值逐条一致。后端新增专家时，这五张表必须同步补
 * 5 条；`PROFILE_NAME_KEYS` 新增条目的同时 **必须**在 11 个语言包补齐对应
 * `stockAnalysis.analystRoles.*` key —— 缺 key 时 i18next 的 `fallbackLng`
 * 会兜到 en-US，再缺就把**原始 key 串**直接显示到界面上。
 *
 * ── 门禁 ──
 * `src/components/settings/__tests__/agentProfileMaps.test.ts` 断言：
 *   ① 五张表 key 集合两两相等；
 *   ② 每个 name/role key 在 11 个语言包中都存在；
 *   ③ key 无重复、无孤儿（不出现表外后缀命名）。
 */

export const PROFILE_NAMES: Record<string, string> = {
  "stock-market-analyst": "市场技术分析师",
  "stock-sentiment-analyst": "情绪面分析师",
  "stock-news-analyst": "消息面分析师",
  "stock-fundamentals-analyst": "基本面分析师",
  "stock-policy-analyst": "政策面分析师",
  "stock-hot-money-tracker": "资金面追踪",
  "stock-lockup-watcher": "筹码限售观察",
  "stock-research-analyst": "研报分析师",
  "stock-sector-analyst": "板块题材分析师",
  "stock-bull-researcher": "多方研究员",
  "stock-bear-researcher": "空方研究员",
  "stock-aggressive-debator": "激进风险评估",
  "stock-conservative-debator": "保守风险评估",
  "stock-neutral-debator": "中性风险评估",
  "stock-research-manager": "研究经理",
  "stock-trader": "交易员",
  "stock-bull-r2": "多方质询（R2）",
  "stock-bear-r2": "空方质询（R2）",
  "stock-bull-r3": "多方终辩（R3）",
  "stock-bear-r3": "空方终辩（R3）",
  "stock-value-investor": "价值投资者（巴菲特框架）",
  "stock-quality-fallback": "保守风险决策师",
  "stock-rule-checker": "规则检查员",
  "stock-catalyst-analyst": "催化剂与叙事分析师",
  "stock-debate-convergence": "辩论收敛官",
  "stock-risk-convergence": "风险收敛官",
  "stock-reflection": "投资复盘官",
  "stock-trend-scanner": "产业趋势扫描器",
  "stock-chain-decomposer": "产业链拆解师",
  "stock-chokepoint-identifier": "瓶颈鉴定师",
  "stock-candidate-mapper": "候选公司映射器",
  "stock-social-media-analyst": "社交媒体分析师",
  "stock-volume-price-analyst": "量价分析师",
  "stock-market-synthesizer": "市场主线综合师",
  "stock-industry-chain-analyzer": "产业链传导分析师",
  "stock-screenshot-diagnoser": "持仓截图诊断师",
  "stock-position-planner": "仓位规划师",
  "stock-stop-loss-reviewer": "止损复查员",
  "stock-explainer": "决策解释官",
};

export const PROFILE_ROLES: Record<string, string> = {
  "stock-market-analyst": "股票分析师",
  "stock-sentiment-analyst": "股票分析师",
  "stock-news-analyst": "股票分析师",
  "stock-fundamentals-analyst": "股票分析师",
  "stock-policy-analyst": "股票分析师",
  "stock-hot-money-tracker": "股票分析师",
  "stock-lockup-watcher": "股票分析师",
  "stock-research-analyst": "股票分析师",
  "stock-sector-analyst": "股票分析师",
  "stock-bull-researcher": "辩论研究员",
  "stock-bear-researcher": "辩论研究员",
  "stock-aggressive-debator": "风险评估师",
  "stock-conservative-debator": "风险评估师",
  "stock-neutral-debator": "风险评估师",
  "stock-research-manager": "决策者",
  "stock-trader": "交易员",
  "stock-bull-r2": "辩论研究员",
  "stock-bear-r2": "辩论研究员",
  "stock-bull-r3": "辩论研究员",
  "stock-bear-r3": "辩论研究员",
  "stock-value-investor": "股票分析师",
  "stock-quality-fallback": "决策者",
  "stock-rule-checker": "风险评估师",
  "stock-catalyst-analyst": "股票分析师",
  "stock-debate-convergence": "辩论研究员",
  "stock-risk-convergence": "风险评估师",
  "stock-reflection": "决策者",
  "stock-trend-scanner": "股票分析师",
  "stock-chain-decomposer": "股票分析师",
  "stock-chokepoint-identifier": "股票分析师",
  "stock-candidate-mapper": "股票分析师",
  "stock-social-media-analyst": "股票分析师",
  "stock-volume-price-analyst": "股票分析师",
  "stock-market-synthesizer": "股票分析师",
  "stock-industry-chain-analyzer": "股票分析师",
  "stock-screenshot-diagnoser": "股票分析师",
  "stock-position-planner": "决策者",
  "stock-stop-loss-reviewer": "决策者",
  "stock-explainer": "决策者",
};

/** profileId → agent_role id（必须与后端 `EXPERT_ROLE_MAP` 的 role 值逐条一致） */
export const PROFILE_ROLE_IDS: Record<string, string> = {
  "stock-market-analyst": "stock-analyst",
  "stock-sentiment-analyst": "stock-analyst",
  "stock-news-analyst": "stock-analyst",
  "stock-fundamentals-analyst": "stock-analyst",
  "stock-policy-analyst": "stock-analyst",
  "stock-hot-money-tracker": "stock-analyst",
  "stock-lockup-watcher": "stock-analyst",
  "stock-research-analyst": "stock-analyst",
  "stock-sector-analyst": "stock-analyst",
  "stock-bull-researcher": "debater",
  "stock-bear-researcher": "debater",
  "stock-aggressive-debator": "risk-evaluator",
  "stock-conservative-debator": "risk-evaluator",
  "stock-neutral-debator": "risk-evaluator",
  "stock-research-manager": "decision-maker",
  "stock-trader": "trader",
  "stock-bull-r2": "debater",
  "stock-bear-r2": "debater",
  "stock-bull-r3": "debater",
  "stock-bear-r3": "debater",
  "stock-value-investor": "stock-analyst",
  "stock-quality-fallback": "decision-maker",
  "stock-rule-checker": "risk-evaluator",
  "stock-catalyst-analyst": "stock-analyst",
  "stock-debate-convergence": "debater",
  "stock-risk-convergence": "risk-evaluator",
  "stock-reflection": "decision-maker",
  "stock-trend-scanner": "stock-analyst",
  "stock-chain-decomposer": "stock-analyst",
  "stock-chokepoint-identifier": "stock-analyst",
  "stock-candidate-mapper": "stock-analyst",
  "stock-social-media-analyst": "stock-analyst",
  "stock-volume-price-analyst": "stock-analyst",
  "stock-market-synthesizer": "stock-analyst",
  "stock-industry-chain-analyzer": "stock-analyst",
  "stock-screenshot-diagnoser": "stock-analyst",
  "stock-position-planner": "decision-maker",
  "stock-stop-loss-reviewer": "decision-maker",
  "stock-explainer": "decision-maker",
};

export const PROFILE_NAME_KEYS: Record<string, string> = {
  "stock-market-analyst": "stockAnalysis.analystRoles.marketAnalyst",
  "stock-sentiment-analyst": "stockAnalysis.analystRoles.sentimentAnalyst",
  "stock-news-analyst": "stockAnalysis.analystRoles.newsAnalyst",
  "stock-fundamentals-analyst": "stockAnalysis.analystRoles.fundamentalsAnalyst",
  "stock-policy-analyst": "stockAnalysis.analystRoles.policyAnalyst",
  "stock-hot-money-tracker": "stockAnalysis.analystRoles.hotMoneyTracker",
  "stock-lockup-watcher": "stockAnalysis.analystRoles.lockupWatcher",
  "stock-research-analyst": "stockAnalysis.analystRoles.researchAnalyst",
  "stock-sector-analyst": "stockAnalysis.analystRoles.sectorAnalyst",
  "stock-bull-researcher": "stockAnalysis.analystRoles.bullResearcher",
  "stock-bear-researcher": "stockAnalysis.analystRoles.bearResearcher",
  "stock-aggressive-debator": "stockAnalysis.analystRoles.aggressiveDebator",
  "stock-conservative-debator": "stockAnalysis.analystRoles.conservativeDebator",
  "stock-neutral-debator": "stockAnalysis.analystRoles.neutralDebator",
  "stock-research-manager": "stockAnalysis.analystRoles.researchManager",
  "stock-trader": "stockAnalysis.analystRoles.trader",
  "stock-bull-r2": "stockAnalysis.analystRoles.bullR2",
  "stock-bear-r2": "stockAnalysis.analystRoles.bearR2",
  "stock-bull-r3": "stockAnalysis.analystRoles.bullR3",
  "stock-bear-r3": "stockAnalysis.analystRoles.bearR3",
  "stock-value-investor": "stockAnalysis.analystRoles.valueInvestor",
  "stock-quality-fallback": "stockAnalysis.analystRoles.qualityFallback",
  "stock-rule-checker": "stockAnalysis.analystRoles.ruleChecker",
  "stock-catalyst-analyst": "stockAnalysis.analystRoles.catalystAnalyst",
  "stock-debate-convergence": "stockAnalysis.analystRoles.debateConvergence",
  "stock-risk-convergence": "stockAnalysis.analystRoles.riskConvergence",
  "stock-reflection": "stockAnalysis.analystRoles.reflection",
  "stock-trend-scanner": "stockAnalysis.analystRoles.trendScanner",
  "stock-chain-decomposer": "stockAnalysis.analystRoles.chainDecomposer",
  "stock-chokepoint-identifier": "stockAnalysis.analystRoles.chokepointIdentifier",
  "stock-candidate-mapper": "stockAnalysis.analystRoles.candidateMapper",
  "stock-social-media-analyst": "stockAnalysis.analystRoles.socialMediaAnalyst",
  "stock-volume-price-analyst": "stockAnalysis.analystRoles.volumePriceAnalyst",
  "stock-market-synthesizer": "stockAnalysis.analystRoles.marketSynthesizer",
  "stock-industry-chain-analyzer": "stockAnalysis.analystRoles.industryChainAnalyzer",
  "stock-screenshot-diagnoser": "stockAnalysis.analystRoles.screenshotDiagnoser",
  "stock-position-planner": "stockAnalysis.analystRoles.positionPlanner",
  "stock-stop-loss-reviewer": "stockAnalysis.analystRoles.stopLossReviewer",
  "stock-explainer": "stockAnalysis.analystRoles.explainer",
};

export const PROFILE_ROLE_KEYS: Record<string, string> = {
  "stock-market-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-sentiment-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-news-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-fundamentals-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-policy-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-hot-money-tracker": "stockAnalysis.analystRoles.analyst",
  "stock-lockup-watcher": "stockAnalysis.analystRoles.analyst",
  "stock-research-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-sector-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-bull-researcher": "stockAnalysis.analystRoles.debateResearcher",
  "stock-bear-researcher": "stockAnalysis.analystRoles.debateResearcher",
  "stock-aggressive-debator": "stockAnalysis.analystRoles.riskAssessor",
  "stock-conservative-debator": "stockAnalysis.analystRoles.riskAssessor",
  "stock-neutral-debator": "stockAnalysis.analystRoles.riskAssessor",
  "stock-research-manager": "stockAnalysis.analystRoles.decisionMaker",
  "stock-trader": "stockAnalysis.analystRoles.trader",
  "stock-bull-r2": "stockAnalysis.analystRoles.debateResearcher",
  "stock-bear-r2": "stockAnalysis.analystRoles.debateResearcher",
  "stock-bull-r3": "stockAnalysis.analystRoles.debateResearcher",
  "stock-bear-r3": "stockAnalysis.analystRoles.debateResearcher",
  "stock-value-investor": "stockAnalysis.analystRoles.analyst",
  "stock-quality-fallback": "stockAnalysis.analystRoles.decisionMaker",
  "stock-rule-checker": "stockAnalysis.analystRoles.riskAssessor",
  "stock-catalyst-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-debate-convergence": "stockAnalysis.analystRoles.debateResearcher",
  "stock-risk-convergence": "stockAnalysis.analystRoles.riskAssessor",
  "stock-reflection": "stockAnalysis.analystRoles.decisionMaker",
  "stock-trend-scanner": "stockAnalysis.analystRoles.analyst",
  "stock-chain-decomposer": "stockAnalysis.analystRoles.analyst",
  "stock-chokepoint-identifier": "stockAnalysis.analystRoles.analyst",
  "stock-candidate-mapper": "stockAnalysis.analystRoles.analyst",
  "stock-social-media-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-volume-price-analyst": "stockAnalysis.analystRoles.analyst",
  "stock-market-synthesizer": "stockAnalysis.analystRoles.analyst",
  "stock-industry-chain-analyzer": "stockAnalysis.analystRoles.analyst",
  "stock-screenshot-diagnoser": "stockAnalysis.analystRoles.analyst",
  "stock-position-planner": "stockAnalysis.analystRoles.decisionMaker",
  "stock-stop-loss-reviewer": "stockAnalysis.analystRoles.decisionMaker",
  "stock-explainer": "stockAnalysis.analystRoles.decisionMaker",
};
